### ISSUE TITLE
Link to Conda seems broken

### ISSUE THREAD

**Issue by behnam2015** [iiasa/message_ix#101]
It seems the link to conda is not working. I don't know if this is a permanent change, but some students couldn't install the package before the course only for this minor issue.

**Comment by gidden** [comment]
Hi Behnam, which link to conda are you referring?

**Comment by behnam2015** [comment]
Thanks Matt! The link to download, under installation section.
https://www.continuum.io/downloads

**Comment by gidden** [comment]
Ah, it looks like they have changed their url. Would you mind making a PR
with the update?

**Comment by behnam2015** [comment]
Sure! Done.

**Comment by gidden** [comment]
I think this can now be closed
