### ISSUE TITLE
Scenario Specific Unit Tests

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#108]
We want to implement some tests that confirm changes in the code base do not affect basic baseline scenarios. This will require a number of steps.

First, we will want to make a `ci` folder inside of `message_ix/tests`. Inside, we want the following files:

- `scenarios.csv`: lists models, scenarios, expected objective function value
- `generate_scenario_db.[py|sh]`: connects to production database, creates new local database, copies models/scenarios in `scenarios.csv` to local database, uploads local database to internal IIASA hosted filesystem accessible from outside. This will require the `ixmp` branch `gidden:newjar`.
- `test_scenarios.py`: 
  - all tests should have a pytest CLI decorator to skip unless a specific flag is provided (e.g., pytest --ci)
  - all tests should have a check that downloads the localdb if not already there
  - single test for each scenario (either explicitly or generated on the fly, we can talk about the best strategy here)
- a `README.md` which explains what each file is for, how to regenerate the data, etc.

We will want to have all passwords required stored in environment variables. This can then be updated in `circleci`.

Finally, we will want to update `.circleci/config.yaml` to update the line which does `pytest tests --ci`

**Comment by danielhuppmann** [comment]
closed as implemented through #109
