### ISSUE TITLE
Seeing non-zero ACT value for a technology without any commodity linked to it 

### ISSUE THREAD

**Issue by Jihoon** [iiasa/message_ix#117]
I have a strange observation, which I want to clarify.

By mistake, I didn't put any 'renewable_potential' values for the historical hydro tec I defined ("hydro_hist") for the entire time horizon, which means its input commodity ("hydro_c_hist") dedicated to the tec has no ground. And input and output parameters were defined only from 1965 and on. But there was historical_new_capacity starting from 1950.

Then in the result, I found that ACT has a value for 2020 for the hydro capacity of year_vtg 1960. (lifetime 60 years). I guess there is a loophole where ACT can still show up when all the input/output/renewable_potential are not defined.
Shouldn't it still give zero ACT if there is no potential defined for modeling years?

**Comment by danielhuppmann** [comment]
If a decision variable does not have any associated costs and is not linked in any constraint, the solver may return any value for that variable.
