### ISSUE TITLE
Circle CI tests fail on PRs from forks

### ISSUE THREAD

**Issue by khaeru** [iiasa/message_ix#143]
For #138, the Circle CI test fails as follows:

```
$ #!/bin/sh -eo pipefail
docker run \
-e MESSAGE_IX_CI_USER=$MESSAGE_IX_CI_USER \
-e MESSAGE_IX_CI_PW=$MESSAGE_IX_CI_PW \
message_ix/message_ix:py2 \
/bin/bash -c 'source activate root && cd /message_ix/tests/ci && ./run_on_ci.sh'
++ set -e
++ python generate_test_file.py
++ python download_license.py
Traceback (most recent call last):
  File "download_license.py", line 29, in <module>
/gams24.8_linux_x64_64_sfx/gams
    'Failed download with user/pass: {}/{}'.format(username, password))
IOError: Failed download with user/pass: /
Exited with code 1
```

However, it does not fail for, e.g. #142, which is from a different fork than mine.

Is there a specific action needed to add these credentials for each fork? If so, these should be documented, and it should be noted (perhaps in the PR template, or elsewhere) when this test is not required; e.g. if a non IIASA developer makes a PR and we cannot share with them a ENE GAMS license file.

**Comment by danielhuppmann** [comment]
Note that @gidden just updated `pyam` to not use CircleCI and instead rely on travis for all OS, see https://github.com/IAMconsortium/pyam/pull/158.

Maybe something to consider here as well?

**Comment by gidden** [comment]
Hi all - yes would suggest moving away from circle. It's been more trouble than it's worth lately.

**Comment by khaeru** [comment]
> Hi all - yes would suggest moving away from circle. It's been more trouble than it's worth lately.

Done by #153, so this issue can be closed.
