### ISSUE TITLE
Reporting Enhancement Proposal A

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#150]
This proposal contributes to #149 

The idea behind this proposal is to develop specific nomenclature/taxonomy of the data such that clearly defined processing steps as well as relationships/dependencies between steps and/or data can be identified.

I propose (prior to any other suggestions/inputs) four classifications of data:

- primitives
- derivatives
- aggregates
- variables

Their relationships are shown in the below figure:

![reporting proposal a 3](https://user-images.githubusercontent.com/1392657/51241229-a6b50b80-197d-11e9-97f2-32ed44d3d8ec.png)

**Comment by danielhuppmann** [comment]
I don't see a reason why there needs to be a translation to "Variables" at the end, in particular because the `groupby vintage_year` is probably not always true.

An easier way would be to identify any of the types 'primitives', 'derivatives' and 'aggregates' by an IAMC-compliant variable.

**Comment by danielhuppmann** [comment]
Another observation: the linearity is not always true. As an example, take energy intensity of GDP. To compute that at the global level, you need to first aggregate, then derive.

**Comment by gidden** [comment]
My initial thought on the "Variables" section is that there we "lose" information from the model. For example, in order to accurately calculate some aggregate, we may need to weight by vintage year. In the IAMC data template, there is no explicit mention of this (i.e., it is message_ix model specific). Thus this would be a interface/processing step invoked after all operations are performed that need message_ix-specific information.

In any case, I completely agree that we should plan to support "optimization" of the process to calculate only those data that users are interested in. Using this proposal, one way would be to:

- take a list of IAMC variables of interest as input
- identify all necessary root nodes (Cost|Fossil Fuel in this case)
- work up the tree to identify necessary aggregates/derivatives/primitives
- initiate the process listing only necessary data

**Comment by khaeru** [comment]
> In any case, I completely agree that we should plan to support "optimization" of the process to calculate only those data that users are interested in. Using this proposal, one way would be to:
> 
> * take a list of IAMC variables of interest as input
> * identify all necessary root nodes (Cost|Fossil Fuel in this case)
> * work up the tree to identify necessary aggregates/derivatives/primitives
> * initiate the process listing only necessary data

The machine learning world has spawned a lot of packages for managing "workflows". [Here's an example from Google's TensorFlow](https://www.tensorflow.org/guide/graphs) (look at the flowchart). The idea is that each item to be calculated depends on its inputs, in a directed acyclic graph (DAG). Identifying a subset of the nodes and edges is called "pruning".

Usually this is done so that, in big data applications, the different operations can be farmed out/parallelized across multiple nodes/languages. MESSAGE doesn't need those features, so e.g. [Luigi](https://luigi.readthedocs.io/en/stable/example_top_artists.html) is overkill. But we could locate and take advantage of existing packages that implements (including pruning) DAGs…e.g. I just stumbled across [Pinball](https://github.com/pinterest/pinball) and there are likely others.

**Comment by OFR-IIASA** [comment]
> 
> 
> Another observation: the linearity is not always true. As an example, take energy intensity of GDP. To compute that at the global level, you need to first aggregate, then derive.

There are numerous different operations required for calculating the global variable. In some cases, for example with capital costs, no value is reported; for prices, we often use the max value and in some cases e.g. for reporting the global price of gas, we actually report the global lng price, therefore requiring a combination of two commodities reported as the same variable; for some variables we will need to calculate using population data i.e. anything that is reported as per capita. Deriving global values is very diverse and what i did is to always recalculate the glb variable in a separate step after calculating regional values.

**Comment by khaeru** [comment]
Closing; will centralize continued discussion on #149 and the linked wiki page.
