### ISSUE TITLE
Reporting Enhancement Proposal B

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/message_ix#151]
This proposal contributes to #149. It builds on #150, but generalizes the conceptual framing. It also uses comments by @khaeru in https://github.com/iiasa/message_ix/wiki/Reporting.

The idea behind this proposal is to develop specific nomenclature/taxonomy of the data such that clearly defined processing steps as well as relationships/dependencies between steps and/or data can be identified.

## Aim

We require a solution to turn the raw GAMS output (dataframes of variables and equations, e.g., `ACT`) into an IAMC-style timeseries table.

## Classifications of operation:

Note that there isn't necessarily a hierarchical order in which these operations are called.

### Primitives

Primitives are data accessible directly from model results without any processing required.

Examples: `activity`, `input`, `new_capacity`

### Derivatives

Derivatives are data that can be calculated directly from primitives or other derivatives. There is a plethora of possible functions here (multiplication, division, shares, growth rates).

Examples: `gdp per capita`

### Aggregates

Aggregates are data that must be aggregated (using any method, e.g., sum, weighted average, etc.) from primitives or derivatives from one or more technologies, or where data is aggregated over regions.

### Finalization

The final operation, doing some clean-up, building up the variable tree, aggregating over regions, and committing (a selection of) the reporting output to the ixmp platform (aka database).

## Architecture

Given the similarities of features like 'derivatives' and 'aggregates' to [pyam](http://software.ene.iiasa.ac.at/pyam/), it makes sense to use a `pyam.IamDataFrame` as the internal data model. Every operation computes a timeseries (identified by an IAMC-style variable, one series for each relevant region) and appends it to the data model.

## Workflow

 - Programmatic: 
    ```
    pp = message_ix.PostProcess(scenario)
    pp.activity('Primary Energy|Wind', technology='wind_ppl')
    ...
    pp.aggregate('Primary Energy)
    pp.finalize()
    ```
 - File-based, using YAML or other syntax.
    ```
    - activity
        - Primary Energy|Wind
            - technology: wind_ppl
    - aggregate
        - Primary Energy
     ```
    called using `message_ix.Scenario.reporting()`
 - Introspective, by examining the sets and category mappings in the model/scenario definition
    Example: every technology having `electricity|secondary` as an ouput

**Comment by OFR-IIASA** [comment]
The first immediate reaction is that aggregates are not always the sum of all reported variables. For example, take Primary Energy|Biomass. The following variables are aggregated under PE Biomass:

Primary   Energy\|Biomass
Primary   Energy\|Biomass\|1st Generation
Primary   Energy\|Biomass\|Electricity
Primary   Energy\|Biomass\|Electricity\|w/ CCS
Primary   Energy\|Biomass\|Electricity\|w/o CCS
Primary   Energy\|Biomass\|Energy Crops
Primary   Energy\|Biomass\|Gases
Primary   Energy\|Biomass\|Hydrogen
Primary   Energy\|Biomass\|Liquids
Primary   Energy\|Biomass\|Modern
Primary   Energy\|Biomass\|Residues
Primary   Energy\|Biomass\|Solids
Primary   Energy\|Biomass\|Traditional
Primary   Energy\|Biomass\|w/ CCS
Primary   Energy\|Biomass\|w/o CCS

The aggregate is only the sum of the last two variables. There are also numerous other variables that are not part of any strict hierarchy, so these cases need to be catered for.

Further, the current practice shows that in some cases an aggregate is calculated prior to calculating all sub-variables.

**Comment by danielhuppmann** [comment]
> The aggregate is only the sum of the last two variables. There are also numerous other variables that are not part of any strict hierarchy, so these cases need to be catered for.

`pyam` already supports that: if you call `aggregate(v)`, it will aggregate all sub-variables to `v` (`'v|*', level=0)`. If you call `aggregate(v, components)`, it will only add up the components. By using `pyam` as the internal data model, we can easily re-use all features there.

**Comment by khaeru** [comment]
Closing; we will centralize continued discussion on #149 and the linked wiki page.
