### ISSUE TITLE
Allow passing args through the `solve()` function

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/message_ix#16]
Currently, one cannot use the `solve()` function to read non-default variables and equations from the solution of a MESSAGE-scheme scenario. We should allow to pass args through the solve function to `read_sol_from_gdx()`.

**Comment by danielhuppmann** [comment]
see this discussion on the googlegroup for more information https://groups.google.com/forum/#!topic/message_ix/2a9VicfhuZw

**Comment by knraj** [comment]
What arguments we have to pass to scenario.solve()

**Comment by danielhuppmann** [comment]
hi @knraj , for solving a standard MESSAGEix instance, you don't need any arguments.

Do you have a more elaborate use case?
