### ISSUE TITLE
Incorrect emission price reporting with different period length

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#167]
When time period duration differs within the model time horizon, then the reported emission prices under the variable "PRICE_EMISSION" have a noticeable drop when moving from five to ten-year time steps as can be seen in the year 2060 (5-year duration) -> 2070 (10-year duration) in the example below

| node | type_emission | type_tec | year_all | 2055 | 2060 | 2070 | 2080 | 2090 | 2100 | 2110 |
|------|----------------|----------|---------|------|------|------|------|------|------|------|
World | TCE | all | Level | 1263 | 1612 | 1472 | 2398 | 3907 | 6364 | 10367

**Comment by danielhuppmann** [comment]
Thanks @OFR-IIASA for raising this issue! I did some digging and identified the culprit.  The fix will be included in the next release.

**Comment by khaeru** [comment]
@danielhuppmann @OFR-IIASA is this resolved by the changes in #178 and other hotfixes in the 1.2 release? If so, we can close it.

**Comment by khaeru** [comment]
> @danielhuppmann @OFR-IIASA is this resolved by the changes in #178 and other hotfixes in the 1.2 release? If so, we can close it.

Since no reply in 5 months, I'll assume yes. If this issue recurs, please open a new one.
