### ISSUE TITLE
platform cloning broken in message_ix

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#174]
At the moment, we support cloning models into different platforms in `ixmp`. This is currently broken in `message_ix` for two reasons:

- the same issue originally found in `ixmp` - the java object was not being passed the correct new platform
- `message_ix.Scenario` defines its own clone function, thus circumventing the fix provided in `ixmp`

This brings up a larger question of polymorphism (PM) and depedency between the two `Scenario` classes. I would suggest when fixing this issue that we also review the current state of PM and try to minimize custom code on the `message_ix` side where possible, depending instead of common PM best practices.

**Comment by gidden** [comment]
cc @zikolach @khaeru @danielhuppmann - we found out why the cloning workflow was not working for `message_ix` scenarios

**Comment by khaeru** [comment]
As mentioned in Slack, `message_ix.Scenario.solve()` does this properly:
https://github.com/iiasa/message_ix/blob/f80ad367c17c303512710d654c6743c8567e5028/message_ix/core.py#L318

`message_ix.Scenario.clone()` should do the same, only adding any extra functionality needed by MESSAGEix.

Another PM issue here is a class hierarchy violation:
https://github.com/iiasa/ixmp/blob/5cff4c86d2fdb9b51679cf37a34ccb9163cfd9c4/ixmp/core.py#L1071-L1091

…note the docstring for this **ixmp** method refers to "MESSAGE-scheme" scenarios. It should not.

**Comment by gidden** [comment]
To note here, the main issue has to do with how the `message_ix.Scenario` class interacts between its `clone` and `__init__` methods vis-a-vis the `ixmp.Scenario` class. They are... funky at best. 

In any case, the `clone` function returns a `Scenario` type specific to each library, so we may need to think more deeply about this.

**Comment by khaeru** [comment]
After consultation with @gidden @zikolach and @danielhuppmann, it seems like the `clone()` method for `ixmp.Scenario` does not need to be overloaded in `message_ix.Scenario`. I will take a stab at removing it (keeping in mind the caveats mentioned here, perhaps adding tests)—will file a new PR.
