### ISSUE TITLE
Python 2.7 reaches end-of-life on 2020-01-01

### ISSUE THREAD

**Issue by khaeru** [iiasa/message_ix#177]
See: https://python3statement.org. There will be no Python 2.8.

Given that there are only 9 months remaining during which Python 2 will be officially supported, we should:
- Consider whether features currently in development (e.g. #149) need to be developed with Python 2 support.
- Plan to deprecate support for Python 2.
- Plan to eventually remove support for Python 2.

This applies across ixmp and other software related to message_ix.

One related task is to identify if there are any current users running message_ix, ixmp, etc. under Python 2.

**Comment by gidden** [comment]
+1 for dropping  python 2 support as python itself does from me

**Comment by danielhuppmann** [comment]
+2 for dropping python 2 support

**Comment by khaeru** [comment]
Do we do this in message_ix 1.2 / ixmp 0.2, or is this a “backwards incompatible” change, i.e for ≥2.0 / ≥1.0? The latter would imply we scheduled those versions for not later than 2020-01-01.

Actions might be:
1. At first, simply remove things that indicate py2 support:
   - Travis configuration for py2.
   - Lines in `setup.py`.
   - Any conda configuration that promises py2 support?
   - Anything else?
2. Then as we go (e.g. when revising individual files), any py2 compatibility code can be stripped out. That is, it doesn't need to be done all at once.
3. Extend the style guide to indicate what changes this implies, if any.

**Comment by danielhuppmann** [comment]
4. The py2-division support in the tutorial notebooks
