### ISSUE TITLE
GAMS Solver

### ISSUE THREAD

**Issue by fkanyako** [iiasa/message_ix#188]
Hi,
I am sorry for the basic questions.
Could you please tell me what solvers, if any I need in addition to the base GAMS module?

Thank you
Franklyn

**Comment by danielhuppmann** [comment]
Thanks @fkanyako for using MESSAGEix and using the GitHub issues for questions!

We are using CPLEX in most applications, and experimenting with GUROBI to see whether this yields better solution times.

In any case, you can easily change that by editing the solver settings in https://github.com/iiasa/message_ix/blob/71ba8881b493d2cfff4dd9fd296ce7557b67fa2d/message_ix/model/MESSAGE/auxiliary_settings.gms#L23 (or if you remove that line, GASM will revert to your default solver).

**Comment by gidden** [comment]
Should we open up a specific issue for including this feature (i.e., to name the solver to use at run time)? I think @khaeru had some ideas and might already have an open issue..?

**Comment by khaeru** [comment]
iiasa/ixmp#119 contains the idea for an `ixmp.Model` abstract base class. The subclass for MESSAGEix could have an attribute for the solver that takes attributes like `CPLEX`, `GUROBI`, and code that ensures it's passed to the GAMS call. That should probably wait until after the pending minor release.

**Comment by gidden** [comment]
Ok great, let's use that issue then for the time being now that it is referenced here. Closing this issue, @fkanyako please let us know if you need any more assistance!
