### ISSUE TITLE
No module named: ixmp

### ISSUE THREAD

**Issue by fkanyako** [iiasa/message_ix#192]
Hi,
I installed MESSAGE via Anaconda, I am trying run the Westeros electrified tutorial to test it. I followed the instructions as far as this command:

import pandas as pd
import ixmp as ix
import message_ix

from message_ix.utils import make_df

%matplotlib inline

We get the following error:
---------------------------------------------------------------------------
ModuleNotFoundError Traceback (most recent call last)
&lt;ipython-input-2-abb2698e3c81&gt; in &lt;module&gt;()
1 import pandas as pd
----&gt; 2 import ixmp as ix
3 import message_ix
4
5 from message_ix.utils import make_df
ModuleNotFoundError: No module named &#39;ixmp&#39;

Can you please advise on what this error means? I assumed installing via Anaconda automatically installed ixmp.

Thanks

**Comment by gidden** [comment]
Hi @fkanyako. If I remember correctly, you installed via Anaconda, which also installs all dependencies (including `ixmp`). Is it possible that your jupyter notebook is in the wrong environment? See, e.g., https://stackoverflow.com/questions/37085665/in-which-conda-environment-is-jupyter-executing

**Comment by gidden** [comment]
You can also check this on the command line with

```
python -c 'import ixmp'
```

**Comment by fkanyako** [comment]
Thank you. 
This suggestion works, jupyter notebook was in the wrong environment. It all works now.

I have another question, am going through the Westeros tutorial, everything works well until this command:
from tools import Plots
p = Plots(scenario, country, firstyear=model_horizon[0])

I get the error: "No module named tools".

I installed a module I searched online called "tools", but that didn't work, I get another error called:
ImportError: cannot import name 'Plots' from 'tools'.

I noticed from the Westeros tutorial on here, there is a script called "tools.py" (https://github.com/iiasa/message_ix/blob/master/tutorial/westeros/tools.py) . 
 Is that the tools we import "Plots' from? how do I install it? If its python package can you please share the name of the package to install?

**Comment by gidden** [comment]
Hi @fkanyako going to close this in favor of #204
