### ISSUE TITLE
Role of "time"-related indexes in commodity balance equation

### ISSUE THREAD

**Issue by behnam-zakeri** [iiasa/message_ix#193]
Having two indexes related to sub-annual time steps in parameter `input`, i.e., `time_origin` and `time`, and two indexes in parameter `output`, i.e., `time_dest` and `time`, creates an expectation that a technology can be active in one sub-annual time step (like Feb) and the input or output commodity (or maybe both?) can be linked to another time step (like Jan). Is this expectation correct? @JulianHunt4 and I tested this linkage and it seems our interpretation is not correct. I created a test to show this, if it is needed, I can make a PR for adding that test. 
This issue is related to `time` and `time2` in `COMMODITY_BALANCE`, where the mapping of time indexs in `duration_time_rel` requires that the time indexes be either the same or one being the parent of another.
I illustrated possible cases in an example where a _conversion_ technology receives fuel from a fuel _supply_ technology to meet the electricity demand in different sub-annual time combinations, shown in the table below. 
![test_time2](https://user-images.githubusercontent.com/30926636/57837684-93973880-77c3-11e9-9781-48369a467eaf.jpg)

**Comment by behnam2015** [comment]
```
"""
This unit test is to make sure COMMODITY_BALANCE works as expected, when the
index "time", "time_dest", and "time_origin" are different for input/output
parameters of a technology.

"""

import ixmp
test_mp = ixmp.Platform()

from message_ix import Scenario

def model_test(comment, time_origin, time_act, time_dest):
    yr = 2020
    scen = Scenario(test_mp, 'test_time', comment, version='new')
    scen.add_set('node', 'node')
    scen.add_set('commodity', ['electr', 'fuel'])
    scen.add_set('level', 'level')
    scen.add_set('year', yr)
    scen.add_set('type_year', yr)
    scen.add_set('technology', ['gas_ppl', 'gas_supply'])
    scen.add_set('mode', 'mode')
    scen.add_set('lvl_temporal', 'season')
    scen.add_set('time', list(set(time_origin + time_act + time_dest)))
    duration = 1 / (len(scen.set('time')) - 1)

    for h in set(time_origin + time_act + time_dest):
        scen.add_set('map_temporal_hierarchy', ['season', h, 'year'])
        scen.add_par('duration_time', [h], duration, '-')

    for h1, h2, h3 in zip(time_origin, time_act, time_dest):
        scen.add_par('demand', ['node', 'electr', 'level', yr, h3], 1, 'GWa')
        supply_spec = [yr, yr, 'mode', 'node', 'fuel', 'level', h1, h1]
        fuel_spec = [yr, yr, 'mode', 'node', 'fuel', 'level', h2, h1]
        electr_spec = [yr, yr, 'mode', 'node', 'electr', 'level', h2, h3]
        scen.add_par('output', ['node', 'gas_supply'] + supply_spec, 1, 'GWa')
        scen.add_par('input', ['node', 'gas_ppl'] + fuel_spec, 1, 'GWa')
        scen.add_par('output', ['node', 'gas_ppl'] + electr_spec, 1, 'GWa')
    scen.commit('scenario setup')
    scen.solve(case=comment)
    act = scen.var('ACT')[scen.var('ACT')['lvl'] > 0]
    assert 'gas_supply' in set(act['technology'])

def test_time_commodity(test_mp):

    # First, 'time_origin', 'time', and 'time_dest' are the same
    comment = 'equal_time'
    model_test(comment, time_origin=['1'], time_act=['1'], time_dest=['1'])

    # Second, different 'time_origin', but 'time' and 'time_dest' are the same
    comment = 'time_origin_different'
    model_test(comment, time_origin=['1'], time_act=['2'], time_dest=['2'])

    # Third, different 'time_dest', but 'time' and 'time_origin' are the same
    comment = 'time_dest_different'
    model_test(comment, time_origin=['1'], time_act=['1'], time_dest=['2'])

    # Forth, different 'time', but 'time_dest' and 'time_origin' are the same
    comment = 'time_act_different'
    model_test(comment, time_origin=['1'], time_act=['2'], time_dest=['1'])
```

**Comment by DIUANA** [comment]
Benham it is a very interesting case. How is it now?

I believe case 4 is a bit non-sense this would be working as a storage change the period of the output o the past.

In case 2 it makes sense to conversion work in Feb even when supply is not unless supply it was not active in Jan either. As far as I understand it is ok beacuse it is getting from the past time.

The one I cannot understand is case 3. I cannot see a reason for the model do not solve it. In my opinion it is analogous to case 2.

Do you have any conclusion on that?

All the Best
Fabio

**Comment by behnam-zakeri** [comment]
@Fabio, thank you for commenting on this. These were cases I tested to see if inter-temporal storage can be done only by setting different `time`, `time_origin`, and `time_dest` in parameters _input_ and _output_. The conclusion was that: no it's not possible with the current setup. That's why we moved to present storage equations explicitly in #190.

**Comment by behnam-zakeri** [comment]
@DIUANA , related to your question, why Case 2 doesn't work. It's related to the parameter _duration_time_rel_. Because, it shows the relative duration of a time index to itself or to its parent, see below:

![image](https://user-images.githubusercontent.com/30926636/85049937-a681f680-b195-11ea-87b2-3ccf82203418.png)

So, in this case, `duration_time_rel(Feb, Jan)` has no value, and as such the commodity balance equation is not working to link the output of _gas_ppl_ to _demand_ in Feb, resulting to an error.

**Comment by behnam-zakeri** [comment]
As confirmed by @danielhuppmann and experiments shown here, COMMODY_BALANCE is not intended to shift commodity between two timesteps at the same temporal level, i.e., represnting storage functionality. As such, explicit storage equations were added to the model through #190 and this issue can be closed. The unit tests developed here will be modified and used in testing COMMODIY_BALANCE for timesteps.

**Comment by DIUANA** [comment]
Many hanks for the explanation @behnam-zakeri
