### ISSUE TITLE
Urgent-solving problem

### ISSUE THREAD

**Issue by mohammadamint** [iiasa/message_ix#195]
Hello,

I have established a model for India. I calibrated all the related data for my model and when I run the model, I get no errors until the scenario.solve ( ) line. I have attached the error. I have to present my model for a course and I am in a harsh situation.
I would appreciate if you can help me.
Regards,
Amin
![1](https://user-images.githubusercontent.com/50955527/58258099-64a83600-7d72-11e9-9de7-e91fd44c7b53.jpg)
![2](https://user-images.githubusercontent.com/50955527/58258101-6671f980-7d72-11e9-9025-86a711e6bdea.jpg)

**Comment by gidden** [comment]
Hi Amin, This kind of error is normally provided when the model is
infeasible. You can check that by looking at the GAMS output in the
terminal in which you opened the notebook. There should also be a *.lst
file that lists related errors.
