### ISSUE TITLE
How to install "tools" module?

### ISSUE THREAD

**Issue by fkanyako** [iiasa/message_ix#204]
Hi,

Am going through the Westeros tutorial, everything works well until this command:

"from tools import Plots
p = Plots(scenario, country, firstyear=model_horizon[0])"

I get the error: "No module named tools".
I installed a module I searched online called "tools", but that didn't work, I get another error called: "ImportError: cannot import name 'Plots' from 'tools'".

I noticed from the Westeros tutorial on here, there is a script called "tools.py" (https://github.com/iiasa/message_ix/blob/master/tutorial/westeros/tools.py).
Is that the tools we import "Plots' from? how do I install it? If its python package can you please share the name of the package to install?

Thank you

**Comment by gidden** [comment]
Hi @fkanyako, the `tools.py` file is packaged with our tutorials. How did you get them? Did you download them via our CLI? See our [docs](https://messageix.iiasa.ac.at/tutorials.html#getting-tutorial-files). If so, you should get that file with the download.

**Comment by fkanyako** [comment]
Thank you Matthew,
 I downloaded the tutorial file again and everything works well. 
As a beginner in MESSAGE, you have been very helpful.

Thank you

Franklyn
