### ISSUE TITLE
Sub-annual time steps limitation

### ISSUE THREAD

**Issue by JulianHunt4** [iiasa/message_ix#210]
There are some numbers of sub-annual time steps that are not compatible to the GAMS formulation. I used a code to test the sub-annual time steps that work and I got the results below:

Number of sub-annual time steps that work:
1, 2, 3, 4, 5, 8, 12, 16, 17, 32, 34, 64, 107, 128, 256, 512, 1024, 2048, 4096, 8192. 

There is trend for 2^n. However, 16384 does not work.

It would be interesting to have 8760 sub-annual time steps working to test the storage module in an hourly resolution. Would it be possible @danielhuppmann ?

**Comment by danielhuppmann** [comment]
thanks @JulianHunt4 for creating this issue. However, the description is not specific enough for me to give you a useful response. From my reading of the GAMS code, I cannot see why 5 time steps or 6 time steps should behave differently in any way.

My suggestion would be to translate your test code into a proper unit test, i.e., the smallest possible case where the incompatibility can be seen.

Please use https://github.com/iiasa/message_ix/blob/master/tests/test_feature_price_commodity.py as an example and create a test file `test_feature_subannual.py` in a new branch and create a PR (then close this issue with a reference to the PR).

Then, we can have an efficient discussion to find out what is wrong - the GAMS code or your testing example, or something else. As a side benefit, we will have a test making sure that sub-annual time steps will always work as expected in the future.

**Comment by JulianHunt4** [comment]
@danielhuppmann thanks for solving the issue in our brief meeting. 
The issue was that the sum of the temporal resolution was not equal to one. 
The code below resolved the issue. This solution is to set the last sub-annual time step temporal resolution to a number to make sure the sum of the temporal resolution equals to one.  

tim = 8760
listofStrings = ['h_1']
listofTemperalResolution = [round(1/tim, 10)]
listofOrder = [1]
c = 2
while c < tim+1:
     listofStrings.append('h_'+str(c))
     listofTemperalResolution.append(round(1/tim, 10))
     listofOrder.append(c)
     c = c + 1
listofTemperalResolution[tim-1] = 1 - sum(listofTemperalResolution[0:tim-1])
time_duration = dict( zip(listofStrings,listofTemperalResolution))  
time_order = dict( zip(listofStrings,listofOrder))

**Comment by danielhuppmann** [comment]
this can be simplified to:
```
names = ['h_{}'.format(i) for i in range(n)]
duration = [round(1/n, d)] * n
duration[n - 1] = 1 - round(sum(duration[:n - 1], d)
```
where `n` is the number of time steps and `d` is the precision (number of digits).

**Comment by behnam-zakeri** [comment]
This issue was addressed by changing the behavior of the respective check in GAMS thourgh #513.
