### ISSUE TITLE
install.bat not working if pyam-iamc package not installed

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#215]
install.bat executes the command `python setup.py install`.  As soon as all the tests are collected and if `pyam-iamc` has not been installed manually, an error is raised that there is no `pyam` package available.  The reason for this behavior is that setup.py does not automatically install those modules required listed under `EXTRAS_REQUIRE`.  

Trying to execute `pip install .[reporting]` instead of the should resolve the issue, but this doesn't seem to work if there are large amounts of gdx files located in the local installation folder. Please see the issue #214.  

In the future, a possibility would be to have an editable install.

**Comment by khaeru** [comment]
@OFR-IIASA and I discussed this in person yesterday & today, with some historical knowledge from @MiguelPobleteCazenave

- install.bat is a relic from days before message_ix was packaged on Conda and PyPI.
- It's currently used by @OFR-IIASA on Windows, and perhaps others to refresh message_ix during development.
- For that purpose, a workaround is:
  - Open the Anaconda Prompt as administrator.
  - `cd` to the directory containing message_ix.
  - Run `pip install --editable .`.
- The script also does the following two things:
  - Installs rmessageix, which is not officially supported.
  - Runs the test suite.

The fix here is to:
1. As an interim measure, change install.bat to execute:
    ```
    pip install --editable .[docs,reporting,tests,tutorial]
    ```
    …instead of `python setup.py install`.
2. Document that:
    - Developers should give the above command in order to install message_ix in their current environment for development purposes.
    - On Windows, these commands should be run in the Anaconda Prompt, and as administrator if the developer has a system (rather than user) install of Anaconda.
3. Eventually remove install.bat.

Similar changes should be made for ixmp.

**Comment by MiguelPobleteCazenave** [comment]
I took a quick look at the install.bat script (without actually running it) and, as @OFR-IIASA said, it seems to me that the error is actually on the setup.py script and not on the install.bat file. So I guess the decision would be whether we want to keep or deprecate this installation option, because it seems to me that this should be a relatively easy fix.
