### ISSUE TITLE
Setup configuration file for cplex.opt

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#216]
With the new release of message_ix, the options for cplex specified in `cplex.opt` have been relocated to core.py.  Nevertheless, an issue that remains is that the standard cplex options specified may not be ideal (e.g. lpmethod 4 should be generally used for the IIASA global model as opposed to the standard lpmethod 2).  If the preferred option though needs to be either specified every time when calling `solve()` it may be more intuitive to have a config file for `cplex.opt` similar to the `default_propoerties` file, which is not part of the repository but is read prior to using the default options specified in `core.py`.  This would avoid:
a. having excess/repetitive code in the solve statement.
b. enable ensuring that tests are always executed using the defaults as opposed to the personal configuration, as lpmethod 4 results in some tests failing.
c. implement a standardized scheme across message_ix, where functions which can be called over the command line interface first take arguments, then look for a configuration file and lastly apply defaults.
d. avoid having to make changes to core.py to set the default solving options to ones personal preferences.

**Comment by khaeru** [comment]
Closed by #557.

For those coming back here later:

> similar to the `default_properties` file

The use of separate properties files (for JDBCBackend config) has been deprecated, and this info is now read through the single user configuration file, or set at runtime.

> ensuring that tests are always executed using the defaults as opposed to the personal configuration

This is done in the test suite via the `tmp_env` fixture (which predates this issue; see iiasa/ixmp#137).

> implement a standard scheme…

This is described at [‘Configuration’ in the ixmp docs](https://docs.messageix.org/projects/ixmp/en/stable/api.html#configuration). To paraphrase, by setting `IXMP_DATA=/foo/bar message-ix command …`, one can point to a directory containing a different ixmp config.json file, in which the abovementioned settings can differ.
