### ISSUE TITLE
Global SSP2 version

### ISSUE THREAD

**Issue by fkanyako** [iiasa/message_ix#226]
Hi,
I need the global version of message_ix with SSP2 as baseline for my research. 
Could you please tell me what is the baseline for the current version of message_ix. And when should we expect the SSP version of message_ix? Especially SSP2?

Thank you
Franklyn

**Comment by khaeru** [comment]
Hi Franklyn,

While the documentation for the MESSAGE-GLOBIOM global model is online (see https://message.iiasa.ac.at/global/ and https://github.com/iiasa/message_doc), the input data workflow and setup- / run scripts are currently not public. The goal is to eventually make them public, but no specific date is set for this.

For research collaborations, please contact the IIASA Energy Program via its [website](https://www.iiasa.ac.at/web/home/research/researchPrograms/Energy/About-Energy-Program.en.html).
