### ISSUE TITLE
Installation: No module named 'pyam' (and further connected issues)

### ISSUE THREAD

**Issue by jkikstra** [iiasa/message_ix#237]
Perhaps connected to #215, when installing `message_ix` following https://message.iiasa.ac.at/en/stable/getting_started.html I get the following error when running the tests:

```
(base) C:\Users\kikstra\Documents\GitHub\message_ix>py.test tests
=============================================== test session starts ================================================
platform win32 -- Python 3.7.3, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
message_ix location: C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\message_ix
ixmp config: {'DB_CONFIG_PATH': None, 'DEFAULT_DBPROPS_FILE': None, 'DEFAULT_LOCAL_DB_PATH': WindowsPath('C:/Users/kikstra/.local/share/ixmp/localdb/default')}
rootdir: C:\Users\kikstra\Documents\GitHub\message_ix
plugins: arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, remotedata-0.3.1
collected 59 items / 1 errors / 58 selected

====================================================== ERRORS ======================================================
_____________________________________ ERROR collecting tests/test_reporting.py _____________________________________
ImportError while importing test module 'C:\Users\kikstra\Documents\GitHub\message_ix\tests\test_reporting.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_reporting.py:15: in <module>
    import pyam
E   ModuleNotFoundError: No module named 'pyam'
================================================= warnings summary =================================================
C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\_pytest\config\__init__.py:545
  C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\_pytest\config\__init__.py:545: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: ixmp.testing
    self.import_plugin(import_spec)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================== 1 warnings, 1 error in 0.37s ===========================================
``` 

Installing pyam manually (`pip install pyam`) and running `py.test tests` gives an error regarding `pycollocation`
```
(base) C:\Users\kikstra\Documents\GitHub\message_ix>py.test tests
=============================================== test session starts ================================================
platform win32 -- Python 3.7.3, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
message_ix location: C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\message_ix
ixmp config: {'DB_CONFIG_PATH': None, 'DEFAULT_DBPROPS_FILE': None, 'DEFAULT_LOCAL_DB_PATH': WindowsPath('C:/Users/kikstra/.local/share/ixmp/localdb/default')}
rootdir: C:\Users\kikstra\Documents\GitHub\message_ix
plugins: arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, remotedata-0.3.1
collected 59 items / 1 errors / 58 selected

====================================================== ERRORS ======================================================
_____________________________________ ERROR collecting tests/test_reporting.py _____________________________________
ImportError while importing test module 'C:\Users\kikstra\Documents\GitHub\message_ix\tests\test_reporting.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_reporting.py:15: in <module>
    import pyam
..\..\..\AppData\Local\Continuum\anaconda3\lib\site-packages\pyam\__init__.py:9: in <module>
    from . initial_guesses import OrthogonalPolynomialInitialGuess
..\..\..\AppData\Local\Continuum\anaconda3\lib\site-packages\pyam\initial_guesses.py:10: in <module>
    import pycollocation
E   ModuleNotFoundError: No module named 'pycollocation'
================================================= warnings summary =================================================
C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\_pytest\config\__init__.py:545
  C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\_pytest\config\__init__.py:545: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: ixmp.testing
    self.import_plugin(import_spec)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================== 1 warnings, 1 error in 0.20s ===========================================
```
Further installing pycollocation gives:
```
(base) C:\Users\kikstra\Documents\GitHub\message_ix>py.test tests
=============================================== test session starts ================================================
platform win32 -- Python 3.7.3, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
message_ix location: C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\message_ix
ixmp config: {'DB_CONFIG_PATH': None, 'DEFAULT_DBPROPS_FILE': None, 'DEFAULT_LOCAL_DB_PATH': WindowsPath('C:/Users/kikstra/.local/share/ixmp/localdb/default')}
rootdir: C:\Users\kikstra\Documents\GitHub\message_ix
plugins: arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, remotedata-0.3.1
collected 59 items / 1 errors / 58 selected

====================================================== ERRORS ======================================================
_____________________________________ ERROR collecting tests/test_reporting.py _____________________________________
ImportError while importing test module 'C:\Users\kikstra\Documents\GitHub\message_ix\tests\test_reporting.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_reporting.py:15: in <module>
    import pyam
..\..\..\AppData\Local\Continuum\anaconda3\lib\site-packages\pyam\__init__.py:12: in <module>
    from . problem import AssortativeMatchingProblem
..\..\..\AppData\Local\Continuum\anaconda3\lib\site-packages\pyam\problem.py:11: in <module>
    from pycollocation import SymbolicTwoPointBVPLike
E   ImportError: cannot import name 'SymbolicTwoPointBVPLike' from 'pycollocation' (C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\pycollocation\__init__.py)
================================================= warnings summary =================================================
C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\_pytest\config\__init__.py:545
  C:\Users\kikstra\AppData\Local\Continuum\anaconda3\lib\site-packages\_pytest\config\__init__.py:545: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: ixmp.testing
    self.import_plugin(import_spec)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================== 1 warnings, 1 error in 0.74s ===========================================
```

**Comment by khaeru** [comment]
> I get the following error when running the tests:
> 
> ```
> Traceback:
> tests\test_reporting.py:15: in <module>
>     import pyam
> E   ModuleNotFoundError: No module named 'pyam'
> ```

This part is a bug in the documentation. setup.py also includes a dependency on `pyam-iamc` as part of the 'reporting' target, but the install instructions don't tell you to specify this.
They should probably say to run `pip install .[tests,reporting]`.

The error with `pycollocation` is because the package https://pypi.org/project/pyam/ is something entirely unrelated; you should `pip install pyam-iamc` (https://pypi.org/project/pyam-iamc/).

**Comment by awais307** [comment]
> > I get the following error when running the tests:
> > ```
> > Traceback:
> > tests\test_reporting.py:15: in <module>
> >     import pyam
> > E   ModuleNotFoundError: No module named 'pyam'
> > ```
> 
> This part is a bug in the documentation. setup.py also includes a dependency on `pyam-iamc` as part of the 'reporting' target, but the install instructions don't tell you to specify this.
> They should probably say to run `pip install .[tests,reporting]`.
> 
> The error with `pycollocation` is because the package https://pypi.org/project/pyam/ is something entirely unrelated; you should `pip install pyam-iamc` (https://pypi.org/project/pyam-iamc/).

I was facing a similar error and wasn't able to use reporting features on my mac, untill I found that `pip install pyam `and `pip install pyam-iamc` are different. Now that I installed `pyam-iamc`.

**Comment by khaeru** [comment]
@GamzeUnlu95 also encountered this issue today. As clarification: one must install `pyam-iamc` *and uninstall* the unrelated `pyam` package. If both are installed, then `import pyam` may import the wrong package.

`pyam-iamc` is a dependency of `message_ix.reporting`, and if the user does e.g. `pip install message_ix[reporting]` the correct package will be installed: https://github.com/iiasa/message_ix/blob/128750720de91317e64c9913f26d7d0a4024fe4f/setup.py#L30-L36

The fix here is still to add a sub-heading under ["Common issues" on the "Installation" page](https://message.iiasa.ac.at/en/stable/getting_started.html#common-issues) describing the issue and explaining the fix.

The labels "help wanted" and "good first issue" are still attached :)

**Comment by GaryKwokQZ** [comment]
> > I get the following error when running the tests:
> > ```
> > Traceback:
> > tests\test_reporting.py:15: in <module>
> >     import pyam
> > E   ModuleNotFoundError: No module named 'pyam'
> > ```
> 
> This part is a bug in the documentation. setup.py also includes a dependency on `pyam-iamc` as part of the 'reporting' target, but the install instructions don't tell you to specify this. They should probably say to run `pip install .[tests,reporting]`.
> 
> The error with `pycollocation` is because the package https://pypi.org/project/pyam/ is something entirely unrelated; you should `pip install pyam-iamc` (https://pypi.org/project/pyam-iamc/).



> @GamzeUnlu95 also encountered this issue today. As clarification: one must install `pyam-iamc` _and uninstall_ the unrelated `pyam` package. If both are installed, then `import pyam` may import the wrong package.
> 
> `pyam-iamc` is a dependency of `message_ix.reporting`, and if the user does e.g. `pip install message_ix[reporting]` the correct package will be installed:
> 
> https://github.com/iiasa/message_ix/blob/128750720de91317e64c9913f26d7d0a4024fe4f/setup.py#L30-L36
> 
> The fix here is still to add a sub-heading under ["Common issues" on the "Installation" page](https://message.iiasa.ac.at/en/stable/getting_started.html#common-issues) describing the issue and explaining the fix.
> 
> The labels "help wanted" and "good first issue" are still attached :)

oh god, Thank you! finally successfully run the shit code.
