### ISSUE TITLE
link to RTD-hosted documentation under Getting Started/Installation section in Readme.md broken

### ISSUE THREAD

**Issue by volker-krey** [iiasa/message_ix#243]
Link to https://message.iiasa.ac.at/en/v1.2/getting_started.html under
https://github.com/iiasa/message_ix/blob/master/README.md#installation is broken.

**Comment by volker-krey** [comment]
Actually, other links to RTD (e.g., tutorials) also seem to be affected.

**Comment by khaeru** [comment]
Good catch @volker-krey—I fixed this for the `1.2.x` maintenance branch in #228, but did not do so on `master`. I will make a hotfix commit (without PR) against `master`.
