### ISSUE TITLE
documentation of parameters only lists dimensions, but lacks description 

### ISSUE THREAD

**Issue by volker-krey** [iiasa/message_ix#260]
https://github.com/iiasa/message_ix/blob/71e52bd1b3635243adbca4a4b5ceddbc487807a8/message_ix/model/MESSAGE/parameter_def.gms#L18

With exception of very few 'general' parameters, a simple of description of parameters is not included in the MESSAGEix documentation and would be very helpful and straight forward to add as this information is included in the parameter definitions in the GAMS code.

**Comment by GamzeUnlu95** [comment]
PR #275 addresses this issue.
