### ISSUE TITLE
Reading new sets and parameters using read_excel

### ISSUE THREAD

**Issue by behnam-zakeri** [iiasa/message_ix#264]
Currently, `read_excel` doesn't read the data of sets and parameters that are not initialized as default in a `message_ix` scenario (i.e., those that are not in `set_list()` and `par_list()`). So, if there is a new set or parameter in a scenario, while it can be exprted to Excel, it cannot be imported back to a new, empty scenario. And the `read_excel` process is halted with an error. This can happen even when importing data of a scenario that has MACRO calibration.

**Comment by behnam-zakeri** [comment]
PR #265 is made to resolve this issue.

**Comment by khaeru** [comment]
#265 was superseded by iiasa/ixmp#286 and eventually iiasa/ixmp#289, which was merged 2020-03-25.
