### ISSUE TITLE
Handle 'year' integer types in message_ix.Scenario

### ISSUE THREAD

**Issue by khaeru** [iiasa/message_ix#268]
MESSAGEix expects parameter dimensions indexed by the set 'year' (including `year_act`, `year_vtg`, and others) to be handled as `int`, rather than `str` for all other dimensions.

This has been handled in ixmp: https://github.com/iiasa/ixmp/blob/c6ae2f74f8d8e1936203abdd79f1d403bb9477bc/ixmp/core.py#L930-L938

However, an ixmp.Scenario need not have any set named 'year'. 'year' could be an equation, parameter, or variable in a valid Scenario. So, that is the wrong place for such code.

Instead, message_ix.Scenario.par should override ixmp.Scenario.par, and then apply this conversion.

Filed via iiasa/message_ix#213.

**Comment by khaeru** [comment]
Per iiasa/ixmp#218, the same conversion should be applied to equ and var, probably by a utility method.

**Comment by zikolach** [comment]
@khaeru continuing discussion to first item of your comment https://github.com/iiasa/ixmp/pull/219#pullrequestreview-321954500

Do you think `message_ix` should override the implementation of `item_get_elements` OR `item_get_elements` should/can be parameterized (be flexible enough) to handle conversion of dimensions to specific dtypes? Wouldn't first lead to greater code duplication and leaking the abstraction of lower level API of ixmp package?

**Comment by khaeru** [comment]
I agree about the first (message_ix overriding Backend or JDBCBackend methods)—clearly should not happen.

The second is a new feature in ixmp that would be nice. I agree it ‘could’ be parametrized; no opinion on whether it ‘should’; whether it ‘can’ depends on if someone has time to implement the new feature. I think it would be a lot of work, e.g. which types are supported; adding tests for all such types, defining an API, etc.

For the actual solution to this issue, see #269.

**Comment by khaeru** [comment]
cc @OFR-IIASA.
