### ISSUE TITLE
years_active() returns wrong years

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#278]
The function years_active() was introduced as part of PR: Adjust to ixmp Backend/Model refactor (#249). The function works when period lengths are all the same, but not when they change and a technology lifetime extends over such a switch in period length.

The issue is traced back to the following line.
data.where(data.age <= lt)['year'].dropna().astype(int).tolist()

Based on an example in the global model: A powerplant built in 1990 with a 30 year lifetime will still be active in 2020, but only for 5 of the 10 year period. The cumulative sum for the years in 2020 will be 35 years, meaning that based on the above line, the returned active_years will only include 2010.

**Comment by OFR-IIASA** [comment]
A proposed solution would be to change:
data.where(data.age <= lt)['year'].dropna().astype(int).tolist()
to
data.where(data.age-data.value <= lt)['year'].dropna().astype(int).tolist()
therefore checking if the cumulative years ('age') - the period length is <= than the lifetime

**Comment by OFR-IIASA** [comment]
A possible solution could be as follows:
Changing the line:
```data.where(data.age <= lt)['year'].dropna().astype(int).tolist()```
to
```data.where(data.age-data.value < lt)['year'].dropna().astype(int).tolist()```

**Comment by khaeru** [comment]
I have agreed to address this and #279 because @OFR-IIASA is working on iiasa/message_data#86 and cannot easily change gears to create a branch with a proposed solution.
