### ISSUE TITLE
vintage_and_active_years() fails when there are no 'year_pairs'

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#279]
in the function vintage_and_active_years(), if active years are requested for a vintage which does not extend into or beyond the first model year, an error occurs in the line:
v_years, a_years = zip(*year_pairs)

a possible solution could be to change this line and the return statement as follows:
from
        v_years, a_years = zip(*year_pairs)
        return pd.DataFrame({'year_vtg': v_years, 'year_act': a_years})
to
        if year_pairs:
                v_years, a_years = zip(*year_pairs)
                return pd.DataFrame({'year_vtg': v_years, 'year_act': a_years})
       else:
                return pd.DataFrame(columns=['year_vtg', 'year_act'])

**Comment by khaeru** [comment]
I have agreed to address this and #278 because @OFR-IIASA is working on iiasa/message_data#86 and cannot easily change gears to create a branch with a proposed solution.
