### ISSUE TITLE
Definition of index name `node_loc` not present in docu

### ISSUE THREAD

**Issue by francescolovat** [iiasa/message_ix#292]
This issue is a follow up discussion of comments in PR#275:
- [Francesco's comment](https://github.com/iiasa/message_ix/pull/275#issuecomment-565036866)
- [Paul's comment](https://github.com/iiasa/message_ix/pull/275#issuecomment-565364522) @khaeru 
- [Daniel's comment](https://github.com/iiasa/message_ix/pull/275#issuecomment-565382195) @danielhuppmann 

It popped up that the definition of index name `node_loc` is not present in docu. It is "hidden" in Java code. I think a definition of these index names should be clarified or at least properly referenced in the documentation, but please correct me if it's not the case.

As a way to easy understand the issue, read Paul's comment below:
@francescolovat —that's a great question. Let's also CC @danielhuppmann @gidden per #254.

There are at least three things going on here:

1. In ixmp (Python/Java code), every dimension of a parameter has both an index **set** and an optional **index/dimension name**.
   - See e.g. the [init_par() docs](https://message.iiasa.ac.at/projects/ixmp/en/master/api-python.html#ixmp.Scenario.init_par).
   - The *sets* must be actual sets in the Scenario.
   - The *names* can be anything; e.g. you can have a dimension indexed by `year` but named `'foo'`.
2. In the MESSAGE GAMS code, there are a number of **aliases for sets**.
   - See [sets_maps_def.gms](https://github.com/iiasa/message_ix/blob/master/message_ix/model/MESSAGE/sets_maps_def.gms).
   - For instance, the lines: https://github.com/iiasa/message_ix/blob/d7a75e63e7d16632c7bd0ed88b0a220b70a8c42b/message_ix/model/MESSAGE/sets_maps_def.gms#L133-L136 show that e.g. `node_share` is always an alias of `node`.
   - This is needed because a GAMS parameter that has the *same* index set for *two* of its dimensions can't re-use the same name, e.g. you can't define a GAMS `parameter foo(year, year);`.
3. See #254. While the GAMS definition of MESSAGE's structure is in the .gms files, there is (must be) a parallel definition of the same structure for the Python code to use. At the moment, this is (wrongly, IMO) hidden in the non-open ixmp_source Java package.
   - See for instance here: https://github.com/iiasa/ixmp_source/blob/6c2afd932e10e284ff12c4a20a0d62372f609228/src/main/java/at/ac/iiasa/ixmp/modelspecs/MESSAGEspecs.java#L877 and here: https://github.com/iiasa/ixmp_source/blob/6c2afd932e10e284ff12c4a20a0d62372f609228/src/main/java/at/ac/iiasa/ixmp/modelspecs/MESSAGEspecs.java#L76-L82
    - These lines are basically equivalent to: `scen.init_par('historical_new_capacity', idx_sets=['node', 'technology', 'year'], idx_names=['node_loc', 'technology', 'year_vtg'])`

So what you've uncovered (I hadn't noticed myself!) is:
- There is not necessarily a correspondence between a **dimension name** on the Python side and any **alias** on the GAMS side.
  - E.g. `node_loc` is a dimension name, but there is no GAMS alias.
  - E.g. `land_emission` is defined over the GAMS alias `location`, but on the Python side it does not have a dimension name.
- Some index names, like `node_loc`, are **hidden in the Java code** and thus the correspondence between them and particular sets can only be guessed at.

I hope this helps to understand the situation and to propose improvements.

_Originally posted by @khaeru in https://github.com/iiasa/message_ix/pull/275#issuecomment-565364522_

**Comment by khaeru** [comment]
No PR was opened for this by the feature freeze for v3.2.0, so we postpone to v3.3 (or later).
