### ISSUE TITLE
better error message for tests failure with wrong installation approach

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#297]
At the moment, if you install `message_ix` with `python setup.py install` or `pip install .` (*without* `-e`/`--editable`), you get the following error when running tests:

```
_____________________________________________________________________________________ ERROR collecting tests/test_nightly.py ______________________________________________________________________________________
tests/test_nightly.py:28: in <module>
    ids, args = zip(*iter_scenarios())
../../../../.local/lib/python3.7/site-packages/message_ix-1.2.0-py3.7.egg/message_ix/testing/nightly.py:77: in iter_scenarios
    with open(HERE.parents[2] / 'tests' / 'data' / 'scenarios.yaml', 'r') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/gidden/.local/lib/python3.7/site-packages/message_ix-1.2.0-py3.7.egg/tests/data/scenarios.yaml'
```

Perhaps it is worth catching this and adding an explicit message stating to install with `pip install . -e`?

**Comment by francescolovat** [comment]
Hi @gidden,

In PR #291 I've handled an issue I was having when testing due to the same reason: that in the _MESSAGEix_ docu was not writted `--editable` in the **Install from source** section.

So, if you select the version v:master in the bottom left then you'd be able to see that the `--editable` is there.

I however don't know how _ReadTheDocs_ works but I'd be nice to force the master version to be loaded by default when anyone accesses the _MESSAGEix_ docu.

Feel free to close this issue if you think I've answered your question.

**Comment by gidden** [comment]
Hey @francescolovat - great to hear that the docs are updated! My suggestion was actually code related, though - something like:

```
try: 
    with open(HERE.parents[2] / 'tests' / 'data' / 'scenarios.yaml', 'r') as f:
...
except FileNotFoundError as e:
   msg = 'Caught error: {}. Did you install with `$ pip install --editable`?'.format(str(e))
   raise FileNotFoundError(msg)
```

See what I mean?

**Comment by francescolovat** [comment]
Hi @gidden,

thanks for the follow up and suggestion. Would this be correct then? (I'm not very familiar with error `logging`)
```
def iter_scenarios():
    try:
        with open(HERE.parents[2] / 'tests' / 'data' / 'scenarios.yaml',
                  'r') as f:
            scenarios = yaml.safe_load(f)

        for id, data in scenarios.items():
            yield id, (
                data['model'],
                data['scenario'],
                data['solve'],
                data.get('solve_options', {}),
                data['cases']
            )
    except FileNotFoundError as e:
        msg = 'Caught error: {}. Did you install message_ix using `$ pip ' \
              'install --editable`?' .format(str(e))
        raise FileNotFoundError(msg)
```

**Comment by gidden** [comment]
Yes that seems reasonable to me!
