### ISSUE TITLE
Update R tutorials to use new Scenario Class

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#31]
Assigning to @adrivinca but perhaps also useful for some YSSPers to take a look? cc: @byersiiasa @scparkinson

**Comment by scparkinson** [comment]
Thanks Matt! The ysspers would like to use python. adriano is finalizing the reticulate utilities for ixmp so we should hoepfully be able to easily collaborate using the ix framework. Fabio will work specifically on translating the R implementation of MESSAGE-Basin to python. More info soon.
