### ISSUE TITLE
Update tests for subannual time slices

### ISSUE THREAD

**Issue by khaeru** [iiasa/message_ix#322]
iiasa/ixmp#264 broke the message_ix test suite:
```
________________________________ test_run_clone ________________________________

tmpdir = local('/tmp/pytest-of-khaeru/pytest-246/test_run_clone0')

    def test_run_clone(tmpdir):
        # this test is designed to cover the full functionality of the GAMS API
        # - initialize a new ixmp platform instance
        # - create a new scenario based on Dantzigs tutorial transport model
        # - solve the model and read back the solution from the output
        # - perform tests on the objective value and the timeseries data
        mp = Platform(driver='hsqldb', path=tmpdir / 'db')
        scen = make_dantzig(mp, solve=True)
        assert np.isclose(scen.var('OBJ')['lvl'], 153.675)
        assert scen.firstmodelyear == 1963
>       assert_frame_equal(scen.timeseries(iamc=True), TS_DF)
E       AssertionError: DataFrame are different
E       
E       DataFrame shape mismatch
E       [left]:  (2, 9)
E       [right]: (2, 8)

message_ix/tests/test_integration.py:26: AssertionError
```

Three other tests in test_integration.py fail in a similar way; all four need to be adjusted to the new behaviour of ixmp.

**Comment by danielhuppmann** [comment]
apologies, the implementation of the subannual-timeseries feature didn't consider all the implications for the `message_ix` framework - my bad.

I suggest to update `ixmp.Scenario.timeseries()` with a new kwarg `subannual` with the following options:
 - `subannual=True`: always return the dataframe with the `subannual` column (current behaviour)
 - `subannual=False`: drop column `subannual` if all values are `'Year'`, else raise an error (previous behaviour)
 - `subannual='auto'` (default): if there are entries of the `subannual` column other than `Year`, return dataframe with that column, else drop that column in returned dataframe

This should make all current tests in `message_ix` pass and provide an intuitive way forward when developing `message_ix` models with subannual resolution.

@khaeru, does that make sense and would that be consistent with the reporting module?

**Comment by khaeru** [comment]
Thanks, this sounds like an elegant solution! So it sounds like it will be resolved with a PR on ixmp, rather than on message_ix.

To your question, this doesn't affect reporting, since:
- we don't have any computations (that I'm aware of) that work with ixmp time-series data rather than model/solution data, and
- A `subannual` dimension is auto-aggregated if users don't explicitly ask for it in reporting outputs—like `mode` or any other.

As for *defaults*, I would suggest:
1. `subannual='auto'` in ixmp 3.0 with a warning.
2. `subannual=True` in ixmp 4.0.

(2) is based on the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment): when they first use `TimeSeries.timeseries()`, the user learns what columns are returned, and they don't need to revise that knowledge *unless* they don't feel like calling `.drop('subannual', axis=1)` on their own. With default `'auto'`, then when a user switches from working on one TimeSeries/Scenario (with only 'Year') to another (with other timeslices), they might be surprised that their code stops working.

@iiasa/ene: any thoughts?

**Comment by zikolach** [comment]
As indicated shortly on the Message meeting - we should carefully think (and test) behavior of `subannual='auto'` flag, as depending on the content of the dataset (e.g. variables having subannual timeslices might be filtered out using variable kwarg). Maybe real-world scenario won't have mixed subannual and non-subannual data, but then we can also think about to warn users adding such data to the scenario (which might be non-trivial).

**Comment by khaeru** [comment]
> we should carefully think (and test) behavior of `subannual='auto'` flag, as depending on the content of the dataset (e.g. variables having subannual timeslices might be filtered out using variable kwarg)

This is a good point. I'd suggest:
- `subannual=True`: no issue.
- `subannual='auto'`: column is included if *any* of the variables contain values other than the default 'Year'.
- `subannual=False`: either `log.warning()` or raise an exception (my preference) if *any* of the variables contain values other than 'Year'.

**Comment by danielhuppmann** [comment]
This approach is more comprehensive but requires additional changes on the Java backend (e.g., a function `has_subannual_data()`. If @zikolach can implement that in a timely manner, ok.

Otherwise, I'd go with the approach outlined above, which can be implemented solely on the Python side.

**Comment by khaeru** [comment]
Can't we just:
```
if whatever_other_conditions and set(data['subannual'].unique()) == {'Year'}:
   data.drop('subannual', axis=1, inplace=True)
```
?

**Comment by zikolach** [comment]
@khaeru that's is most straightforward solution. Alternatively (as previously suggested @danielhuppmann) it can be done via [changing java](https://github.com/iiasa/ixmp_source/pull/280). The difference is that former solution can have different result (with or without subannual column) depending on filters and subset of data returned, while the latter one - depending only on existing timeseries data (in DB and cache).

**Comment by zikolach** [comment]
> * ~`subannual=False`: either `log.warning()` or raise an exception (my preference) if _any_ of the variables contain values other than 'Year'.~

Not sure whether this is still active proposal - but I agree we should raise an exception, otherwise we can have duplicates

**Comment by danielhuppmann** [comment]
Yes, this is the active proposal - as indicated in [my comment](https://github.com/iiasa/message_ix/issues/322#issuecomment-602062671) above, calling this with `subannual=False` will raise an error if there are subannual data.

**Comment by khaeru** [comment]
Just for posterity, I confirm that the four tests in test_integration.py now pass with ixmp `master`.
