### ISSUE TITLE
Attribute Error in the Austrian tutorial regarding Vintage and Active Year

### ISSUE THREAD

**Issue by aaronliuqy** [iiasa/message_ix#330]
Hi. I am trying to run the Austrian RES example in Jupyter notebook (I tried in Spyder as well) and when I execute the command lines 
'year_df = scenario.vintage_and_active_years()
vintage_years, act_years = year_df['year_vtg'], year_df['year_act']'
I get these errors. 
![Error](https://user-images.githubusercontent.com/63275812/78628525-ef305000-78c6-11ea-8249-4b12f341bc5b.png)
It is apparently a problem with Java conversions. Does it have anything to do with my JDK version?
Help is much appreciated.

**Comment by khaeru** [comment]
Can you please run `pip list` on a command-line and tell us which versions of ixmp, message-ix, and JPype1 you have installed?

**Comment by aaronliuqy** [comment]
I have the following version installed.
ixmp 2.0.0
message ix 2.0.0
JPype1 0.7.2

**Comment by khaeru** [comment]
> JPype1 0.7.2

We have some known issues with JPype 0.7.2 (eg. iiasa/ixmp#279) although the symptoms are not the same as this one. Can you please try `pip install JPype1==0.7.1`?

Also CC @zikolach since the Java code to be returning an string where some kind if list is expected.

**Comment by zikolach** [comment]
@khaeru `java.lang.String[]` - array of strings, `getCatEle` returns array of strings from Java. I would check what kind of exception is triggered in try clause as according to [documentation](https://jpype.readthedocs.io/en/latest/userguide.html#converting-from-java-to-python) arrays should be converted to JArray:
```
def to_pylist(jlist):
    """Convert Java list types to :class:`list`."""
    try:
        return list(jlist[:])
    except Exception:
        # java.LinkedList
        return list(jlist.toArray()[:])
```

**Comment by aaronliuqy** [comment]
I installed Jpype 0.71 and it showed an error 'graphviz not installed'. I later installed graphviz as well.
![Jpype1](https://user-images.githubusercontent.com/63275812/78673627-fd0cc200-7914-11ea-954f-d29c903d0152.png)

However when I tried to run messageix again this error popped up.
![Error2](https://user-images.githubusercontent.com/63275812/78674138-bf5c6900-7915-11ea-91ba-ec75d3ef3b14.png)
Changing string conversion to False does not solve the problem.

**Comment by zikolach** [comment]
@aaronliuqy not sure (as not use Windows), but maybe https://github.com/iiasa/message_data/issues/108#issuecomment-597663689 can help you:
> Note this iiasa/ixmp#278 (comment): if conda installs JPype1 version 0.7.2 and then pip install JPype1==0.7.1 downgrades it, the tests seem to fail. OTOH if JPype1 0.7.1 is installed into a clean environment, the tests pass.

**Comment by aaronliuqy** [comment]
@zikolach when I install Jpype 0.7.1 in a clean environment (i.e reinstalled anaconda) I still need to install messageix package which comes with Jpype1 version 0.7.2, then it comes back to the original error. Could you maybe clarify what is a 'clean environment' please. Thank you

**Comment by zikolach** [comment]
I don't know what was meant in the original reference, but can you try `pip uninstall --yes JPype1 && pip install --no-cache-dir JPype1==0.7.1`

**Comment by aaronliuqy** [comment]
I have tried the above command and this is the error I get. Jpype1 is now in version 0.71.
![Error3](https://user-images.githubusercontent.com/63275812/78683647-241dc080-7922-11ea-8763-f4a42ac2109c.png)

**Comment by zikolach** [comment]
@aaronliuqy just to make sure - did you restart kernel in jupyter after re-installing JPype1 package?

**Comment by aaronliuqy** [comment]
@zikolach Yes I did. I have tried it in Spyder as well and the same error pops up.

**Comment by aaronliuqy** [comment]
Hi. Installing Jpype version 0.70 solves all the mentioned issues above. Thank you very much for your help.
