### ISSUE TITLE
 Add the link to mathematical representation of the scenario generator

### ISSUE THREAD

**Issue by github-wbx** [iiasa/message_ix#333]
As mentioned in the MESSAGE-GLOBIOM framework, energy demand are generated using scenario generator, but it does not give a clear introduction about the scenario generator. If possible add the link to mathematical representation of the scenario generator?

**Comment by khaeru** [comment]
The scenario generator that was used with earlier versions of the MESSAGE model (before the creation of this message_ix package) is no longer in use, and there is no plan to make the old code available.

cf. iiasa/message_doc#47

**Comment by github-wbx** [comment]
Thank you for your replying.
So, whether the latest version of the Message_ix  package contains new code be applied to preject energy demand by calling related modules
