### ISSUE TITLE
No JVM shared library file (jvm.dll) found. JAVA_HOME environment variable

### ISSUE THREAD

**Issue by byersiiasa** [iiasa/message_ix#35]
Issue arises in second cell of tutorial when running
`mp = ix.Platform(dbtype='HSQLDB')`

Error is:
`No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.
`
This can occur when `message_ix` has been installed from command line using regular command prompt or WIndows PowerShell

Try installing `message_ix` package using Anaconda Prompt. This can solve the issue

Suggestion: update installation instructions to use Anaconda Prompt.

**Comment by gidden** [comment]
Hey @byersiiasa I'm not sure exactly what is going on here. Would you be willing to make a PR with your suggested changes?

**Comment by byersiiasa** [comment]
@gidden ok will do

**Comment by jkikstra** [comment]
Me, and multiple other new users of message ran into this issue when installing MESSAGE (through Anaconda) when running `mp = ix.Platform(dbtype='HSQLDB')`.

By installing JDK (needs admin rights) and subsequently manually setting the JAVA_HOME system variable (https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html), the problem can be resolved.

**Comment by jkikstra** [comment]
This issue has been addressed by adding instructions to the installation page under "Common Issues".
See #287
