### ISSUE TITLE
GAMS system directory not specified

### ISSUE THREAD

**Issue by bassamjaved** [iiasa/message_ix#357]
Hi,

I'm a new user on a MacBook.

When I try to run code scenario.solve() in one of the tutorials (Westeros), I receive the following error: 

**com.gams.api.GAMSException: GAMS system directory is both not specified and not found from your environment!**

As per the installation instructions, to include the path to the GAMS program in the PATH environment variable, I have added the following line to the end of .bash_profile:

**export PATH=$PATH:/Applications/GAMS29.1**

I am not sure if I have specified the path to the correctly, as I still receive the above error.

Thanks,

Bassam

**Comment by zikolach** [comment]
You can add GAMS **sysdir** to the system path as follows:

```
export GAMS_PATH=/Applications/GAMS29.1/Resources/sysdir
export PATH=$PATH:${GAMS_PATH}
```
