### ISSUE TITLE
How to run MESSAGE-Macro

### ISSUE THREAD

**Issue by aaronliuqy** [iiasa/message_ix#359]
I have been running a MESSAGE model in Jupyter notebook using scenario.solve(). This just does a MESSAGE stand-alone run. I cannot find in the tutorial how to run it with macro. Sorry if this is a simple question, help appreciated.

**Comment by khaeru** [comment]
This is a result of #315; please see https://github.com/iiasa/message_ix/issues/315#issuecomment-641836610 for a suggestion.
