### ISSUE TITLE
Need to install ixmp before

### ISSUE THREAD

**Issue by DIUANA** [iiasa/message_ix#37]
Hi guys,

Just as suggestion you might expose that we need to install the ixmp model before isntal the message_ix model.

Regards
Fabio Diuana

**Comment by gidden** [comment]
Hi Fabio, our readme lists this explicitly for the "advanced" users: https://github.com/iiasa/message_ix#install-from-source-advanced-users

I think we can close this. Thanks!

**Comment by DIUANA** [comment]
Hi.

Thanks, Matthew.

Regards
Fabio
