### ISSUE TITLE
ixmp has not been configured

### ISSUE THREAD

**Issue by sajid209** [iiasa/message_ix#373]
I am working on Electricity supply for Pakistan.
Yesterday, I updated message-ix and faced the problem of the configuration of ixmp.
Need help

![image](https://user-images.githubusercontent.com/62458843/85653512-1a695500-b6e8-11ea-9228-a315f67bbb27.png)

**Comment by khaeru** [comment]
> I updated message-ix

These messages indicate that you have not actually successfully updated message_ix and ixmp to the latest versions. They are generated by an older version of the code, from before version 3.0. `pip list` or `conda list` will show which older version is currently installed.

Please see the [latest install instructions](https://docs.messageix.org/en/latest/getting_started.html), and perhaps try again from a clean state (i.e. uninstall everything). When you have successfully installed version 3.0 of both packages, the command `message-ix show-versions` shown in those instructions will confirm so. When you manage to do so, then please close this issue.

Finally, when submitting issues, please paste the error message(s) as text, not as a screenshot.

**Comment by sajid209** [comment]
Both issues are resolved after following the instruction.

Thanks a lot.
Stay blessed.
