### ISSUE TITLE
Issue in execution of "solve()" class

### ISSUE THREAD

**Issue by sajid209** [iiasa/message_ix#374]
I was working on the Tutorials for developing the understanding of the working of the MESSAGE Model.
I have to extend this to the calculation of long term energy supply for the country.
I am working with GAMS Version 30.3.0

In all cases My model , "Westeros" , "Austian_energy_system", on running "solve()" command;

GAMS core program runs successfully and creates both Input and Output GDX files 
But the Jupyternote book shows the following error and doesn't proceed further.

TypeError: Ambiguous overloads found for at.ac.iiasa.ixmp.objects.MsgScenario.readSolutionFromGDX(str,str,str,java.util.LinkedList,java.util.LinkedList,bool) between:
	public void at.ac.iiasa.ixmp.objects.MsgScenario.readSolutionFromGDX(java.lang.String,java.lang.String,java.lang.String,java.util.List,java.util.List,boolean) throws at.ac.iiasa.ixmp.exceptions.IxException
	public void at.ac.iiasa.ixmp.objects.Scenario.readSolutionFromGDX(java.lang.String,java.lang.String,java.lang.String,java.util.LinkedList,java.util.LinkedList,boolean) throws at.ac.iiasa.ixmp.exceptions.IxException

**Comment by khaeru** [comment]
This issue has the same cause as #373. The error messages are due to an incompatible version of the JPype dependency. Once you successfully install message_ix 3.0, you will get JPype 0.7.5 or greater, and these messages will not occur.
