### ISSUE TITLE
Soft-constraints formulation - re-implementation

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#379]
The current formulation of the soft constraints allow a very rapid growth.

Discussions with @volker-krey @behnam-zakeri and @danielhuppmann concluded in a re-implementation of the soft constraints based on MESSAGE-V.

**Comment by LauWien** [comment]
@OFR-IIASA, is this closed via https://github.com/iiasa/message_ix/pull/474?

**Comment by OFR-IIASA** [comment]
@LauWien correct. This issue is closed via #474
