### ISSUE TITLE
Extend CI checks for released versions via Conda

### ISSUE THREAD

**Issue by khaeru** [iiasa/message_ix#386]
At https://github.com/iiasa/message_ix/issues/383#issuecomment-673435615 @ClaraLuisa reported an issue installing and running the latest release of ixmp and message_ix (3.0). After further investigation (thanks @francescolovat), it turns out:

- The (ixmp, message_ix, jpype1) combination (3.0.0, 3.0.1, 0.7.5) worked *at the time those versions were released*.
- The same combination *does not* work today. It produces the `TypeError: can't apply this __setattr__ to _jpype._JClass object` reported in the other thread. This means that deliberately installing JPype 0.7.5 (e.g. `conda create --name foo --quiet message-ix jpype1=0.7.5`) does not produce a working installation.
- The cause of this change is unclear. It must have to do with changes in conda, one of the other dependencies as packaged for conda, the JPype conda packaging, or similar.
- Our current CI checks do not cover this failure:
  - Checks 'anaconda' and 'miniconda' (added by #358) install the latest conda build of *all* packages, i.e. currently (3.0.0, 3.0.1, 1.0.2).
    This is also not a working combination; @ClaraLuisa and @francescolovat confirm that it produces the same `TypeError: No matching overloads` that was resolved by https://github.com/iiasa/ixmp/pull/351#issuecomment-673441038, shortly after the 3.0 releases. The check passes, because only `message-ix show-versions` and `ixmp ... list` are run, rather than more complex code.
  - Checks 'pytest' and 'nightly' install the `master` branches of ixmp and message_ix.

## Solution

Extend the 'anaconda' and/or 'miniconda' checks to:
- Run at least one test, e.g. one of the tutorials, or other code that touches JPype.
- Install at least one specific version of JPype, e.g. 0.7.5, in addition to the latest version packaged for conda.

## Comments

The number and complexity of dependencies (conda, JPype, etc.) means that we can't monitor/plan for changes in those packages and/or their conda builds. However, a check like this can allow us to detect them early and respond. Since we use a linear release strategy, our only response to these issues is to make new releases from `master`. We do not keep a `3.x` maintenance branch, and consequently test/release from that independently of `master`.

**Comment by francescolovat** [comment]
thanks @khaeru for describing all the process in detail, and also its solution.

**Comment by ClaraLuisa** [comment]
thank @khaeru and @francescolovat for raising this issue. As a quickfix, until this issue has been attended to, would you have any recommendation on how to produce a working message-ix installation on a windows machine?

**Comment by khaeru** [comment]
Installation from source (the `master` branch of both ixmp and message_ix) always works and is frequently tested.

**Comment by ClaraLuisa** [comment]
> Installation from source (the `master` branch of both ixmp and message_ix) always works and is frequently tested.

Thanks @khaeru , this works super smooth!

**Comment by khaeru** [comment]
This issue to be addressed after the 3.1 release.

**Comment by khaeru** [comment]
Another thought: perhaps this should be added as a nightly check in ixmp, since that catches the issue at the lower level where it actually occurs.

**Comment by khaeru** [comment]
No one was assigned to do this by the feature freeze for v3.2.0, so we postpone to v3.3 (or later).

**Comment by Thrameos** [comment]
@khaeru is there an issue that JPype 1.2.x won't work for this project?   0.7.5 is pretty far back.   If you have an issue with the newest, perhaps I can help resolve it.

**Comment by khaeru** [comment]
> is there an issue that JPype 1.2.x won't work for this project? 0.7.5 is pretty far back. If you have an issue with the newest, perhaps I can help resolve it.

@Thrameos many thanks for coming over to inquire!

In short, no issue with 1.2.0, and new installs will get that, so they'll be fine. No need to make any changes in JPype.

I think we can just bump the JPype minimum version; no harm in doing so.

But this issue is more about our own continuous integration (CI) and testing workflows, that let us spot such situations, which could recur in the future. I put some explanation here, mainly for the benefit of my colleagues:
- We release new versions of message_ix (this project) and ixmp (the upstream dependency), let's say version 4.0.
- It depends on a minimum version of JPype (or any other package!)—for instance, say 1.9.
- Then there are new JPype releases, e.g. 2.0, 2.1, 3.0 and so on.
- We adjust ixmp `master` to be compatible with latest JPype.
- However, these changes are not released immediately. Some of our users are still using the last release of ixmp/message_ix.
- Our CI workflows check with (a) the latest release of JPype; that is, the build runner installs from scratch so it picks up the latest version and (b) the `master` branches of ixmp and message_ix.
- Consequently, we miss some test cases:
  JPype | ixmp/message_ix | Tested?
  -- | -- | --
  latest on PyPI, e.g. 2.1 | `master` | Yes (via PyPI)
  latest on conda-forge, e.g. 2.1 | last release, e.g. 4.0 | Yes (via conda)
  minimum in last ixmp release, e.g. 1.9 | last release | No
  minimum in last ixmp release | `master` | No

This issue exists only to say we should test these latter two. They will tell us when we need to bump the minimum version of a dependency. pandas is one example of a project that does this using a clear process, see e.g. [here](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html#increased-minimum-versions-for-dependencies).

P.S. It also helps a lot (thanks!) that JPype now uses semantic versioning: if we see a 2.0.0 release of JPype, that will be a signal to us to do careful, manual checks (until that is automated per this issue), whereas if we see 1.2.1 or 1.3.0, we don't need to be so thorough.

**Comment by Thrameos** [comment]
Sounds good.  There were a few versions with memory leaks between 0.7.5 and 1.2.x as well as some significant speed ups.  There are only a hand full of planned features for JPype (though the last 3 are biggies), so hopefully we will have long term stability point this year.

Regarding sematic versioning, the next likely incompatibility that I am aware of is regards to the type used when automatic converting a Python type.   Current versions of JPype convert a Python int into java.lang.Long and Python float into java.lang.Double, but this is an implementation detail as both were supposed to be converted to java.lang.Number.  You would have to cast to get a specific type.   The documentation for 1.x states it will be java.lang.Number but I can see people using the implementation side effect.   So I am still struggling to figure out if this is a major or a minor change.   It has always been a bug to assume the types when automatically converting an Object (after all it may end up as java.lang.String or null depending on what happened in Python)  but decisions long ago still come back to haunt.    The change is happening as the result of adding a reverse bridge so that Python types can be passed into Java and maintain their identity (and be callable from Java).  Codes that are using Java method with strong typed interfaces are unlikely to notice any changes, so I think that it will be transparent to this project.

**Comment by khaeru** [comment]
Great, thanks for that heads-up—we'll be sure to look out for it.

**Comment by khaeru** [comment]
Removed milestone. Time allocated for wrestling with CI in the 3.3 release cycle has been eaten up by #473, so this will be handled later.
