### ISSUE TITLE
model folder changed, should R rmessage_ix update consequently?

### ISSUE THREAD

**Issue by adrivinca** [iiasa/message_ix#39]
I noticed that after the most recent updates the model folder with the gams files has been moved inside a sub-folder message_ix/message_ix/model.
the `solve` function under the MESSAGE scheme is not working anymore because of this change.
So I was wondering, is it a definitive structure we want to have for the repository? should I update the package accordingly?

**Comment by gidden** [comment]
Yes, this structure is necessary in order to have the public installs.
Namely, the model files are now installed along with the rest of the
package. I'm not sure what the best strategy is here.. but there is now a
model_path() function that could be used.
