### ISSUE TITLE
auto documentation of two individual equations in the storage section of model_core.gms missing

### ISSUE THREAD

**Issue by volker-krey** [iiasa/message_ix#405]
In the storage section of the MESSAGEix equation system, only one of the three equations comes with inline auto documentation code. This should be fixed by also adding documentation for the two additional equations (STORAGE_BALANCE_INIT and STORAGE_EQUIVALENCE).

**Comment by khaeru** [comment]
No one was assigned to do this by the feature freeze for v3.2.0, so we postpone to v3.3 (or later).
