### ISSUE TITLE
Assignment of `capacity_factor` is not properly working for subannual time slices

### ISSUE THREAD

**Issue by behnam-zakeri** [iiasa/message_ix#409]
In `message_ix\model\MESSAGE\data_load.gms`, there are two equations (see the links below) related to the assignment of `capacity_factor`:
1. The first equation assigns `capacity_factor = 1` to the missing entries for `capacity_factor` in any time slice. 
https://github.com/iiasa/message_ix/blob/6f3d0b2daa6ad8421fd045fd51962016e17ec3b4/message_ix/model/MESSAGE/data_load.gms#L141

2. The second equation calculates an average yearly value for `capacity_factor`:
https://github.com/iiasa/message_ix/blob/6f3d0b2daa6ad8421fd045fd51962016e17ec3b4/message_ix/model/MESSAGE/data_load.gms#L145

The problem is that, in a scenario with sub-annual time slices, e.g., two seasons of _winter_ and _summer_; when a technology is active only in sub-annual time slices, it has no `capacity_factor` defined for time `year`. As such, Eq. No. 1 above adds a `capacity_factor` with the value of 1 for `year`. Then, Eq. No 2 above makes an average yearly capacity factor by considering all time slices, including winter, summer, and `year`. This results in an average `capacity_factor` higher than 1, which is not correct.

To tackle this issue, it seems the solution is to reverse the order that these two equations appear in the formulation, i.e.,:
- first caculating the average yearly `capacity_factor`, and then,
- if there is no capacity_factor for `year`, assiging the value of 1 to that.

**Comment by khaeru** [comment]
@behnam-zakeri could you help us interpret here:
- Is this the same issue as #515, or distinct?
- Will it be fixed by #561, or should remain open?

**Comment by behnam-zakeri** [comment]
@khaeru thanks for picking this. No, this is a separate issue. Indeed, this will remain an issue even after the improvements in #561 . So, it should remain open.

**Comment by behnam-zakeri** [comment]
However, now that we have tests for `capacity_factor`, it should be possible to resolve this and test it. I will give it a try, but perhaps after the release.

**Comment by khaeru** [comment]
Thanks! Adjusted the milestone accordingly.

**Comment by glatterf42** [comment]
When I tried to understand the problem here, I found the following: basically, the existing `test_capacity_factor_time(request)` seems to set exactly the conditions that we want: a scenario, where we only have values for `capacity_factor` in the subannual time slices for `winter` and `summer`, but not for `year`. So, according to the description, I'd expect a value of 1 to be added for `year`, which would then go on to disturb the calculation of the average yearly value. However, when I introduce 
```
    cf = scen.par("capacity_factor")
    print(cf)
```
in the test (and look at pytest's output for this test by running with the `-rP` option), I find
```
  node_loc technology  year_vtg  year_act    time  value unit
0     node    gas_ppl      2020      2020  summer    0.8    -
1     node    gas_ppl      2020      2020  winter    0.6    -

```
So I don't see any addition beyond the two specified season. Is this issue obsolete, then? Because if no arbitrary value for `year` is added, the yearly average should also be fine, shouldn't it?

**Comment by behnam-zakeri** [comment]
@glatterf42 thanks, for checking this. Indeed, as you noted, there is no problem in the input data of `capacity_factor`. That is what we can see when calling `Scenario.par("capacity_factor")`. However, when the input data is passed to GAMS, there will be further modifications in `capacity_factor` before using that in the mathematical model. You can see the final `capacity_factor` in the output GDX file.

**Comment by behnam-zakeri** [comment]
The workaround for resolving this issue is proposed in this[ commit](https://github.com/iiasa/message_ix/pull/680/commits/08ef0c75f441e29d9281e56faf78f6c0b293a49c). But we need to extend `test_feature_capacity_factor` to test that.
