### ISSUE TITLE
`bottleneck` dependency installation

### ISSUE THREAD

**Issue by francescolovat** [iiasa/message_ix#442]
When running tests in `message_data`, `test_iamc_replace_units[R11]` was failing due to a missing module/dependency `bottleneck` (not included in `message_data` dependencies).

Trying to fix that problem and `pip` installing `bottleneck`, the following error occurred:

`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

I had to go to that website and install that Visual Studio component to be able to install it.

However, after discussing with @khaeru , this last step probably wouldn't have been needed if trying to install it using `conda` (specifically using `conda-forge` channel).

Possible conclusion:
> We may need to make bottleneck a requirement for the conda (rather than PyPI) package for ixmp or message-ix.

It also may be interesting to have a Windows user to test that installation and making `test_iamc_replace_units[R11]` to pass.

**Comment by glatterf42** [comment]
I haven't seen this issue come up in my time at IIASA. In addition, I have just searched all of ixmp, message_ix, message-ix-models, and message_data, and none includes a test called `test_iamc_replace_units`. Furthermore, the dependencies have changed a lot in the last three years, so I'm assuming that this dependency is either always installed when it is needed or not needed anymore. I will therefore close this issue, but please re-open this or open a new one if it is actually still relevant.
