### ISSUE TITLE
add option for strict equality of `COMMODITY_BALANCE` equation

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/message_ix#47]
There are certain technologies/levels where an inequality for the `COMMODITY_BALANCE` (i.e., SUPPLY > DEMAND) is not applicable, like electricity or pollutants.

We need to define a new equation in the GAMS formulation that implements strict equality as an option.

The question at this point is how to "activate" the strict equality. Should this be contingent on the `commodity` only, or `(commodity, level)`, or also be specific on `node`, `year` or sub-annual `time`.

**Comment by adrivinca** [comment]
for now, in our specific application with water technologies, we found it useful to have the equation contingent on `commodity,level`

**Comment by adrivinca** [comment]
Shall we close this?

**Comment by danielhuppmann** [comment]
this will be closed as part of release 1.2 (merged PR #172 into the release-candidate branch)

**Comment by khaeru** [comment]
Closing as this is now in `master` and 1.2 will be released shortly.
