### ISSUE TITLE
Extend documentation to guide users through Westeros tutorials

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#475]
After having removed the numbering of all Westeros tutorials in PR #450 , some guidance is required for users so that they:
a. know where to start
b. know which set of tutorials belong together
c. understand in what order to do tutorials e.g. which are basics and which are more advanced.

**Comment by LauWien** [comment]
While extending the tutorials with explanations in https://github.com/iiasa/message_ix/pull/524, I noticed there was a difference between the recommended structure of the Westeros baseline tutorial [here](https://github.com/iiasa/message_ix/blob/v3.4.0/tutorial/westeros/westeros_baseline.ipynb) and the documentation [here](https://iiasa-energy-program-message-ix.readthedocs-hosted.com/en/stable/tutorials.html#westeros-electrified). I have updated both files now [here](https://github.com/iiasa/message_ix/pull/524/files#diff-9c16474c20e0255d0285ac8f8732949f08a0c9d5f2500f8084b5e49c2352d500) and [here](https://github.com/iiasa/message_ix/pull/524/files#diff-637f03b972ad59d099d682d441ae5750bbd414834f411a76ab50124d31bc0b83). @OFR-IIASA would you think with this adjustments a. and b. are addressed? I see point c. is possible missing. What do you think?

**Comment by LauWien** [comment]
As stated by @OFR-IIASA in slack, the following tutorials are basics:
- westeros_baseline.ipynb
- westeros_emissions_bounds.ipynb
- westeros_emissions_taxes.ipynb
- westeros_fossil_resource.ipynb
- westeros_baseline_using_xlsx_import_part1.ipynb
- westeros_report.ipynb

which leaves the following to more advanced tutorials:
- westeros_firm_capacity.ipynb
- westeros_flexible_generation.ipynb
- westeros_renewable_resource.ipynb
- westeros_seasonality.ipynb
- westeros_share_constraint.ipynb
- westeros_soft_constraints.ipynb
- westeros_addon_technologies.ipynb
- westeros_baseline_using_xlsx_import_part2.ipynb

However, as stated, the tutorials themselves are not hard, but the substance is not the thing that a new user should start of with in the beginning.
