### ISSUE TITLE
improve documentation of capacity variables `CAP` and `CAP_NEW`

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/message_ix#48]
The decision variables concerning capacity `CAP` and `CAP_NEW` are in the same unit, but concern a different temporal dimension.

`CAP_NEW` is the amount newly installed in one year.
`CAP` is the amount installed at the end of a (usually multi-year) period.

So in the first year of installation, it usually holds that `CAP = CAP_NEW x period_duration` (assuming newly built capacity is not immediately decommissioned, which is mathematically possible).

The difference needs to be better explained in the documentation and tutorials, because it has created some confusion...

**Comment by LauWien** [comment]
In #524 this issue is partially addressed. A better explanation is implemented in the Westeros baseline tutorial. To close this issue a more detailed explanation should be added in the documentation.
