### ISSUE TITLE
conda/macOS install requires channel_priority strict

### ISSUE THREAD

**Issue by marek-iiasa** [iiasa/message_ix#480]
**Summary:** without `conda config set channel_priority strict`—i.e. with the default setting of `flexible`—conda chooses to install JPype1 from the (main) anaconda channels, rather than from conda-forge. The resulting combination of packages does not work. This has been reproduced only on macOS.

**Fix:** Add the above command to step 6 of the install instructions, the one reading “Configure conda to install message_ix from the conda-forge channel:”.

**Temporary mitigation:** if encountering the errors below, give the command directly during installation.

# Original description

Verification of the newly (earlier today) installed message_ix shows the diagnostics copied below (the conda  version is shown at the bottom). No errors/warnings were shown during the installation by: conda install message-ix.
Please check, if something needs to be done.
Thanks,
Marek

```
(msg_env) Ba4:~ marek$ message-ix show-versions
Traceback (most recent call last):
  File "/Users/marek/anaconda3/envs/msg_env/bin/message-ix", line 6, in <module>
    from message_ix.cli import main
  File "/Users/marek/anaconda3/envs/msg_env/site-packages/message_ix/__init__.py", line 4, in <module>
    from ixmp import ModelError, config
  File "/Users/marek/anaconda3/envs/msg_env/site-packages/ixmp/__init__.py", line 7, in <module>
    from .backend.jdbc import JDBCBackend
  File "/Users/marek/anaconda3/envs/msg_env/site-packages/ixmp/backend/jdbc.py", line 14, in <module>
    import jpype
  File "/Users/marek/anaconda3/envs/msg_env/site-packages/jpype/__init__.py", line 18, in <module>
    import _jpype
ModuleNotFoundError: No module named '_jpype'
(msg_env) Ba4:~ marek$ conda list message-ix
# packages in environment at /Users/marek/anaconda3/envs/msg_env:
#
# Name                    Version                   Build  Channel
message-ix                3.3.0              pyhd8ed1ab_0    conda-forge
(msg_env) Ba4:~ marek$ conda --version
conda 4.10.1
(msg_env) Ba4:~ marek$ 
```

**Comment by khaeru** [comment]
@marek-iiasa I've added the triple backticks (\`\`\`) around the pasted console output, which makes it easier to read.

```
ModuleNotFoundError: No module named '_jpype'
```
This line indicates that JPype, in particular the compiled binaries that accompany it, were not correctly installed as required by ixmp via message-ix.

Can you please give:
1. The full output of `conda list`, including JPype, and
2. The output of `python -c "import jpype; print(jpype.__version__)"`?

The latter is likely to fail. As mitigation you might try uninstalling and reinstalling JPype.

**Comment by marek-iiasa** [comment]
Here is the result  of:
(msg_env) Ba4:~ marek$ python  -c "import jpype; print(jpype.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/marek/anaconda3/envs/msg_env/site-packages/jpype/__init__.py", line 18, in <module>
    import _jpype
ModuleNotFoundError: No module named '_jpype'

The conda list is in the attached file:
[conda_lst.txt](https://github.com/iiasa/message_ix/files/6603179/conda_lst.txt)

**Comment by marek-iiasa** [comment]
Attempt to remove JPype failed:
(msg_env) Ba4:~ marek$ conda remove JPype
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - jpype

-----
Also installing was not successful:
(msg_env) Ba4:~ marek$ conda install jpype
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - jpype

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
------

**Comment by marek-iiasa** [comment]
I've noticed that jpype1 was installed but I have no idea if also jpype is needed

**Comment by khaeru** [comment]
> The conda list is in the attached file:
> [conda_lst.txt](https://github.com/iiasa/message_ix/files/6603179/conda_lst.txt)

The contents appear like this:
```
jpeg                      9d                   hbcb3906_0    conda-forge
jpype1                    1.2.1            py37hf7b0b51_0  
jsonlines                 2.0.0              pyhd3deb0d_0    conda-forge
```
Note that most other packages are installed from the conda-forge channel, but jpype1 is installed from the default channel. This may be the cause of the problem: binary compatibility is only expected between conda-packages from within the *same* channel. Un- and re-installing (from conda-forge) might fix this.

> I've noticed that jpype1 was installed but I have no idea if also jpype is needed

Indeed: the package name for the purpose of (un)installation is `jpype1`; but within Python code, it is imported as `jpype`. These names don't need to match, e.g. `message-ix` vs. `message_ix`. Please try `conda remove jpype1` and then `conda install jpype1` and report the results.

**Comment by marek-iiasa** [comment]
Thanks for the tip: removing and installing jpype1 went OK, it is now from conda-forge:
jpype1                    1.2.1            py37h737db71_0    conda-forge
BUT something went wrong:
(msg_env) Ba4:~ marek$ message-ix show-versions
-bash: message-ix: command not found
Also python does not import jpype1
(msg_env) Ba4:~ marek$ python -c "import jpype1"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'jpype1'
(msg_env) Ba4:~ marek$ python --version
Python 3.7.10
----
(msg_env) Ba4:~ marek$ conda list message-ix
# packages in environment at /Users/marek/anaconda3/envs/msg_env:
#
# Name                    Version                   Build  Channel
message-ix                1.0.0                         3    conda-forge

**Comment by marek-iiasa** [comment]
I tried the following:
After removing message-ix python imports jpype:
(msg_env) Ba4:~ marek$ python --version
Python 3.7.10
(msg_env) Ba4:~ marek$ python -c "import jpype; print(jpype.__version__)"
1.2.1
---
but import of jpype1 failed (although it remained in the conda list)
---
After installing message-ix again python continues to import jpype (but not jpype1)
---
Unfortunately, message-ix still does not work:
-bash: message-ix: command not found

**Comment by marek-iiasa** [comment]
one more try:
after conda update message-ix, the original problem comes back:, i.e., 
message-ix show-versions
displays same errors, jpype1 is from the default channel, and python cannot import jpype

**Comment by marek-iiasa** [comment]
I also noticed that removing jpype1 and installing it back results in a much short list of packages: before removing the list has 219 lines, after installing back only 21 lines.  Removing ipype1 removes also message-ix....

**Comment by marek-iiasa** [comment]
Attached are conda lists list[1-4].txt correspond to the following stages:
1. before jpype1 remove
2. after jpype1 remove
3. after jpype1 install
4. after message install
The list after  message-ix update the list is the same as lst1i

Maybe this experiment will help in fixing the problem?

[lst4.txt](https://github.com/iiasa/message_ix/files/6604827/lst4.txt)
[lst1.txt](https://github.com/iiasa/message_ix/files/6604828/lst1.txt)
[lst2.txt](https://github.com/iiasa/message_ix/files/6604829/lst2.txt)
[lst3.txt](https://github.com/iiasa/message_ix/files/6604830/lst3.txt)

**Comment by khaeru** [comment]
First, as mentioned in Slack, I think my explanation above (https://github.com/iiasa/message_ix/issues/480#issuecomment-855388135) was not clear enough—sorry:

>  [T]he package name for the purpose of (un)installation is `jpype1`; but within Python code, it is imported as `jpype`. These names don't need to match, e.g. `message-ix` vs. `message_ix`.

To expand:
- The name `jpype1` is used **only** for installing the package from PyPI/Conda/Conda-forge. To install "jpype" is never needed or possible.
- The name `jpype` is used **only** within Python code, for importing that **same** package. To "import jpype" is never needed or possible.

Per the outputs:

> 1. before jpype1 remove
> 2. …
> 3. …
> 4. after message install
>    The list after  message-ix update the list is the same as lst1i
> 
> [lst1.txt](https://github.com/iiasa/message_ix/files/6604828/lst1.txt)
> [lst4.txt](https://github.com/iiasa/message_ix/files/6604827/lst4.txt)

In both these cases, as well as in your other https://github.com/iiasa/message_ix/issues/480#issuecomment-855440720, message-ix 1.0.0 and ixmp 0.1.2 are installed. These are not the current versions; they are years out of date. (`message-ix show-versions` does not, and will never, work when these versions are installed, because this command-line program did not exist in version 1.0.0.)

Somehow, your system/conda installation is in a state where it is trying to install message-ix 1.0.0. I suspect this may have to do with the order of channels in your conda configuration:
```
Current channels:

- https://conda.anaconda.org/conda-forge/osx-64
- https://conda.anaconda.org/conda-forge/noarch
```

message-ix 1.0.0 was the last version published as architecture-specific versions (i.e. in the "osx-64" and other analogous channels). All recent versions are published in, and should be installed from, the "noarch" channel.

Can you please…
- Try `conda install message-ix>=3.4`? This should force conda to find the more recent version from the "noarch" channel.
- If that fails, please remove the environment entirely (in order to clear any misconfiguration) and retry from the start of the installation instructions.
- Remember to use triple backticks when copying console output, as I mentioned above: https://github.com/iiasa/message_ix/issues/480#issuecomment-854625731. See also the [GitHub Markdown help](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by marek-iiasa** [comment]
I've removed the previously create env., created a new one. The attempt to run:
'''conda install message-ix>=3.4'''
failed (I interrupted after more than 5 min).
Attempts to install with '''-c https://conda.anaconda.org/conda-forge/noarch''' failed (with reported errors).

Finally, I installed by running:
'''conda install -c https://conda.anaconda.org/conda-forge/osx-64 message-ix'''
but ...
'''message-ix show-versions
Traceback (most recent call last):
  File "/Users/marek/anaconda3/envs/msgenv/bin/message-ix", line 6, in <module>
    from message_ix.cli import main
  File "/Users/marek/anaconda3/envs/msgenv/site-packages/message_ix/__init__.py", line 4, in <module>
    from ixmp import ModelError, config
  File "/Users/marek/anaconda3/envs/msgenv/site-packages/ixmp/__init__.py", line 7, in <module>
    from .backend.jdbc import JDBCBackend
  File "/Users/marek/anaconda3/envs/msgenv/site-packages/ixmp/backend/jdbc.py", line 14, in <module>
    import jpype
  File "/Users/marek/anaconda3/envs/msgenv/site-packages/jpype/__init__.py", line 18, in <module>
    import _jpype
ModuleNotFoundError: No module named '_jpype' '''
The current package list is in 
[lst5.txt](https://github.com/iiasa/message_ix/files/6607700/lst5.txt)

**Comment by marek-iiasa** [comment]
I've just tried (in a new environment) the following. Maybe the diagnostics could help in solving the problem?

'''(msg_en) Ba4:msg marek$ conda install "message-ix>=3.4"
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - message-ix[version='>=3.4']

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.'''

**Comment by awais307** [comment]
@marek-iiasa I was experiencing similar nature of errors you posted in your issue today. I realized, I was missing Java Development Kit (JDK) on my OS. I installed JDK for my macOS from [here](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html) and added JAVA_HOME to path variable. After reinstalling message-ix I don't experience errors with jpype and it seems to work fine for me.

**Comment by marek-iiasa** [comment]
Thanks, Muhammad. I'll try your solution soon. Below I provide info promised to Paul a minute ago.
'''(msg_en) Ba4:wrksp marek$  message-ix show-versions
Traceback (most recent call last):
  File "/Users/marek/anaconda3/envs/msg_en/bin/message-ix", line 6, in <module>
    from message_ix.cli import main
  File "/Users/marek/anaconda3/envs/msg_en/site-packages/message_ix/__init__.py", line 4, in <module>
    from ixmp import ModelError, config
  File "/Users/marek/anaconda3/envs/msg_en/site-packages/ixmp/__init__.py", line 7, in <module>
    from .backend.jdbc import JDBCBackend
  File "/Users/marek/anaconda3/envs/msg_en/site-packages/ixmp/backend/jdbc.py", line 14, in <module>
    import jpype
  File "/Users/marek/anaconda3/envs/msg_en/site-packages/jpype/__init__.py", line 18, in <module>
    import _jpype
ModuleNotFoundError: No module named '_jpype' '''
[lst6.txt](https://github.com/iiasa/message_ix/files/6609196/lst6.txt)

**Comment by awais307** [comment]
I realized the error is perhaps relevant to conda installation and not JDK while I tested one more time.
For me installing message-ix through `pip install message-ix` works while installing through `conda install message-ix` still shows jpype error.

**Comment by marek-iiasa** [comment]
Unfortunately.... the solution suggested by Muhammad does not work. I installed JDK, add to $PATH /Library/Java/Home/bin, removed all previously defined (related to message_ix) env, created new env, and from there, and installed message-ix>=3.3. The verification error persists, and the list of packages is the same.

**Comment by marek-iiasa** [comment]
I will now recreate the env, and install message through pip, as suggested by Muhammad.

**Comment by marek-iiasa** [comment]
Thanks to the Muhammad original and additional tips, I succeeded to install message-ix using pip instead of conda. The main points to remember (especially for less experienced colleagues, like myself) when installing on macOS:
1. jdk has to be installed and /Library/Java/Home/bin added to $PATH
2. in newly created env there is no pip; thus, the first step: conda install pip
3. next: pip install message-ix  (I didn't insist on version >= 3.3; ver 3.3 was installed)
4.  message-ix show-versions will complain about missed pyam and reporter
5. next: conda install pyam  (although maybe pip install pyam would be safer); no need to explicitly install reporter
6. message-ix show-versions reported no errors; the reported versions are in lst9.txt 
7. the conda-listed packages are in lst8.txt
[lst8.txt](https://github.com/iiasa/message_ix/files/6610208/lst8.txt)
[lst9.txt](https://github.com/iiasa/message_ix/files/6610209/lst9.txt)

Hope this experience will help to improve the docs; maybe also the missing JDK should be reported (or at least commented in docs)?

**Comment by khaeru** [comment]
Thanks for this report and @awais307 for the assistance.

> Hope this experience will help to improve the docs; maybe also the missing JDK should be reported (or at least commented in docs)?

What we have here is a **workaround** that gets a working install. Conda is still misbehaving in some way that we still have not diagnosed. So it remains to (a) figure out what is actually going wrong and (b) fix it. This may involve adjusting the docs, or not; at the moment, we can't yet tell.

**Comment by khaeru** [comment]
I went through and added \`\`\` to ~3 comments. In several others, ''' (single quotes) was used. Code fencing requires backticks. On my keyboard this is the same key as "~", to the left of the "1" in the number row.

**Comment by marek-iiasa** [comment]
I am sorry for confusing ``` and '''; will try to avoid this.

**Comment by khaeru** [comment]
Updated title, description, and labels to reflect @awais307's discovery that the problem was a missing `channel_priority strict` setting for conda. This turns out to be a docs issue: if users are instructed to set this setting when installing, then the problem should not occur.

**Comment by OFR-IIASA** [comment]
a good way way to check if the channels are set correctly - the command `$ cat .condarc` should show:
```
channels:
  - conda-forge
  - defaults
channel_priority: strict

**Comment by francescolovat** [comment]
Also related to this topic:

The following sequence of commands helped a user getting `message-ix` correctly installed, starting from scratch:


```
conda config --prepend channels conda-forge
 conda config --set channel_priority strict
 conda create --name message_env
 conda activate message_env
 conda install message-ix
```

**Comment by gorkemgungormetu** [comment]
> Also related to this topic:
> 
> The following sequence of commands helped a user getting `message-ix` correctly installed, starting from scratch:
> 
> ```
> conda config --prepend channels conda-forge
>  conda config --set channel_priority strict
>  conda create --name message_env
>  conda activate message_env
>  conda install message-ix
> ```

I am instructing my students to install MESSAGE-ix on their computers but it seems to take very long with output `Solving environment: failed with initial frozen solve. Retrying with flexible solve.`. I also changed my `.condarc` file including `channel_priority: strict` and `allow_conda_downgrades: true` but could not reduce the installation time. I checked it in conda issues but those issues are for installation failures and I can install MESSAGE-ix.
