### ISSUE TITLE
Adress CI failures in test_reporter_from_westeros

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#498]
The test `message_ix/tests/test_reporting.py::test_reporter_from_westeros` began to fail during PR [#478](https://github.com/iiasa/message_ix/pull/478) on all testet python versions (3.6, 3.8 and 3.9) on macOS and Ubuntu, and on python version 3.6 on Windows. At first glance the test run successfully with python versions 3.8 and 3.9 on Windows. However, opening the "Run test suite using pytest" for both versions, it seems the test fails also ([link](https://github.com/iiasa/message_ix/runs/3338664552?check_suite_focus=true)).

https://github.com/iiasa/message_ix/runs/3338664331?check_suite_focus=true#step:17:154

```
_________________________ test_reporter_from_westeros __________________________

self = MultiIndex([('Westeros Electrified', 'baseline', 'Westeros', ...),
            ('Westeros Electrified', 'baseline', 'W...ctrified', 'baseline', 'Westeros', ...)],
           names=['model', 'scenario', 'region', 'variable', 'unit', 'year'])
level = 'value'

    def _get_level_number(self, level) -> int:
        count = self.names.count(level)
        if (count > 1) and not is_integer(level):
            raise ValueError(
                f"The name {level} occurs multiple times, use a level number"
            )
        try:
>           level = self.names.index(level)
E           ValueError: 'value' is not in list

../../../../hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/pandas/core/indexes/multi.py:1426: ValueError
```

**Comment by khaeru** [comment]
- Per #499, the cause was a change in the behaviour of pyam-iamc from version 1.0.0 to 1.1.0.
- The test function `test_reporter_from_westeros()` (but not the actual reporting code) relied on this behaviour.
- The previous behaviour was unadvertised and untested in pyam, so it's not really a bug that it changed; we simply adjust to the new behaviour.

Thanks @LauWien!
