### ISSUE TITLE
Mistakes in documentation of the parameters

### ISSUE THREAD

**Issue by ClaraLuisa** [iiasa/message_ix#51]
Some parameters are described inaccurately on http://messageix.iiasa.ac.at/. eg  "historical_emission" should be something like:
 - node | type_emission | type_tec | type_year 

instead it reads:

- node | emission | type_tec | year

**Comment by khaeru** [comment]
I came across this while looking for documentation-related issues.

The docstring seems to correctly match the definition:
https://github.com/iiasa/message_ix/blob/154c58150755f1445ed48de028656daefccde995/message_ix/model/MESSAGE/parameter_def.gms#L483-L487

The parameter is used here:
https://github.com/iiasa/message_ix/blob/154c58150755f1445ed48de028656daefccde995/message_ix/model/MESSAGE/model_core.gms#L1701-L1708

As far as I can tell:
- The historical emissions are added to projected emissions *for each species*—i.e. each member of the set `emission`, e.g. "CO2", "CH4", etc.—separately.
- *After* this, emissions are summed across sets of species (e.g. "GHG"s) appearing in `type_emission`.
- `year_all` is the set of all historical *and* future years.
- Other parameters like `bound_emission` may be defined as applying not only to particular years, but to "cumulative" emissions; "cumulative" is a member of `type_year` with the special meaning "sum across `year_all`".
- But, historical emissions are specific to particular `year`s.

So the definition and description here seem to be correct.

Can @OFR-IIASA, @danielhuppmann or someone else confirm this is the right interpretation?

**Comment by francescolovat** [comment]
Hi @ClaraLuisa ,

have you found other innaccuracies like the one you presented here?

**Comment by francescolovat** [comment]
@ClaraLuisa I saw there are inconsistencies when defining the sets `node` and `node_loc` to describe dimensions of different parameters... Do you know which is the criteria of them? Please see my comment on this in the #275 for a detailed description of it.

**Comment by ClaraLuisa** [comment]
@khaeru thank you for the explanation. I was confused as both definitions work for adding the parameter.

**Comment by glatterf42** [comment]
I'm closing this issue since @khaeru's understanding seems to be correct. As far as I can tell, @francescolovat tried adapting the parameter definition as suggested here, which didn't work. He then reverted the change because it "ha[d] no sense and [was] wrong", so if it is an actual error or if you find any new errors, please create a new issue for them :)
