### ISSUE TITLE
Address CI failures in the workflow "Install from conda-forge"

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#518]
The job "Check" within the "Install from conda-forge" GitHub Action workflow fails with the following error message:

https://github.com/iiasa/message_ix/runs/3812369811?check_suite_focus=true

```
message-ix: D:\a\_temp\bdcbacfc-6fdb-4503-8522-b897f70c34fa.ps1:6
Line |
   6 |  message-ix show-versions
     |  ~~~~~~~~~~
     | The term 'message-ix' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.

Error: Process completed with exit code 1.
```

Looking at the packages in the job "Install message-ix", message-ix as well as ixmp are not installed in their latest version.

**Comment by khaeru** [comment]
From the output of `conda info` in any of the failing jobs:
```
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
```
Note that the arch-specific (win-64) channels appear _before_ the corresponding noarch channels. This seems to be conda's default. Together with strict channel priority, I think this forces conda to find message-ix 1.0.0 (in win-64) and refuses to consider 3.x in noarch. If we go back to the last passing run [here](https://github.com/iiasa/message_ix/actions/runs/1306436245), the channels are in the same order, but `conda config --set channel_priority strict` is not included.

Re-reading, I think our mistake might have been like this:
- #480 reported that channel_priority strict was required _on macOS only_.
- #501 updated the documentation and also the conda.yaml workflow file.
- However, the workflow _only runs on Windows_, and not on macOS: https://github.com/iiasa/message_ix/blob/f4317125eabb563ed24f6ac7b6c6827711f56f35/.github/workflows/conda.yaml#L17-L19
- So channel_priority strict **need not** be given in this case, and the errors show us that it actually **must not** be given.

Things we could/should do:
1. Remove channel_priority strict while conda.yaml runs only on Windows.
2. Extend the matrix for conda.yaml to also run on macOS.
3. With (2), confirm whether channel_priority strict should/should not be given on each OS.
4. Update the documentation to distinguish.

**Comment by LauWien** [comment]
Ah, perfect, thank you!! :)
