### ISSUE TITLE
Fix handling of activity years and life time of technologies in the tutorials

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#525]
Secondly, as observed in the follow-up discussions on the last capacity building workshop, when we add parameters where the index includes both vintage and activity years, then in the past we have just added activity years that stretch the entire model horizon, irrespective of the lifetime of the technology. This definitely needs to be fixed as this causes too much confusion for new users.

_Originally posted by @OFR-IIASA in https://github.com/iiasa/message_ix/issues/502#issuecomment-908102971_

**Comment by awais307** [comment]
I think this issue is relevant beyond tutorials. While trying to add data frames for new technologies in the global model using `make_df`  , the `year_act` and `year_vtg` are not mapped according to technical_lifetime
