### ISSUE TITLE
GAMS compilation errors re: `time_relative`

### ISSUE THREAD

**Issue by khaeru** [iiasa/message_ix#546]
#### Code sample or context

Tried to run a scenario from the CLI, e.g.:

```
$ message-ix --url="ixmp://local/ENGAGE_SSP2_v4.1.7/EN_NPi2020_1000f" solve --remove-solution
```
#### Expected result

Scenario solves.

#### Problem description

The scenario does not solve. I see:
```
ixmp.model.base.ModelError: GAMS errored with return code 2:
    There was a compilation error                                        
                                    
For details, see the terminal output above, plus:
Listing   : /home/khaeru/vc/iiasa/message-ix/message_ix/model/MESSAGE_run.lst
Input data: /home/khaeru/vc/iiasa/message-ix/message_ix/model/data/MsgData_ENGAGE_SSP2_v4.1.7_EN_NPi2020_1000f.gdx
```

GAMS listing files are attached ([MESSAGE_run.lst.2022-01-27.txt](https://github.com/iiasa/message_ix/files/7948604/MESSAGE_run.lst.2022-01-27.txt)); key lines are:

```
1793  duration_time_rel(time,time2)$( Not time_relative(time) ) = 1 ;
****                                                  $141
**** LINE    109 INCLUDE     /home/khaeru/vc/iiasa/message-ix/message_ix/model/MESSAGE/data_load.gms
**** LINE     77 INCLUDE     /home/khaeru/vc/iiasa/message-ix/message_ix/model/MESSAGE/model_setup.gms
**** LINE     65 INPUT       /home/khaeru/vc/iiasa/message-ix/message_ix/model/MESSAGE_run.gms

…

141  Symbol declared but no values have been assigned. Check for missing
        data definition, assignment, data loading or implicit assignment
        via a solve statement.
        A wild shot: You may have spurious commas in the explanatory
        text of a declaration. Check symbol reference list.
257  Solve statement not checked because of previous errors
492  Symbol not in GDX
```

Per the "wild shot" suggestion, I removed the explanatory text from the declaration of time_relative, and this seems to fix the problem:
```
…
    balance_equality(commodity,level)       mapping of commodities-level where the supply-demand balance must be maintained with equality
* flag for treating unit of ACT in sub-annual time slices relative to parent 'time' (=activating parameter 'duration_time_rel')
    time_relative(time)
;
```
There is no comma, but perhaps the (=) or other characters are the problem. At first glance, I'm not sure why this doesn't offend GAMS on CI.

#### Versions

<details><summary>Output of <tt>message-ix show-versions</tt></summary>

```

ixmp:        3.3.0
     08533cb (HEAD -> main, tag: v3.4.0rc1, tag: v3.4.0, iiasa/main) Mark v3.4.0 in release notes
message_ix:  3.3.1.dev1+g56611ad.d20210630
     315b4f9 (HEAD -> main, iiasa/main) Address failing "Install from conda-forge" workflow (#541)
message_ix_models: 2021.4.8.dev5+g338d44a
     436332f (HEAD -> main, tag: v2022.1.26rc1, tag: v2022.1.26, origin/main, origin/HEAD) Mark v2022.1.26 in doc/whatsnew
message_data: 2020.6.21.dev872+g6c848d83
     0588751c (HEAD -> transport-2022-W04, iiasa/transport-2022-W04) Remove mypy exclusions for transport modules

click:       8.0.1
dask:        2022.01.0
genno:       installed
     d4f0d4b (HEAD -> main, tag: v1.9.1, origin/main) Update copyright year
graphviz:    0.14.2
jpype:       1.3.0
… JVM path:  /usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so
openpyxl:    3.0.7
pandas:      1.4.0
pint:        0.18
xarray:      0.20.2
yaml:        5.4.1

iam_units:   installed
     00857b7 (HEAD -> main, tag: v2021.11.12rc1, tag: v2021.11.12, origin/main) Add nightly tests (#33)
jupyter:     1.0.0
matplotlib:  3.3.4
plotnine:    0.8.0
pyam:        0.11.0

GAMS:        24.9.1

python:      3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0]
python-bits: 64
OS:          Linux
OS-release:  5.13.0-23-generic
machine:     x86_64
processor:   x86_64
byteorder:   little
LC_ALL:      None
LANG:        en_CA.UTF-8
LOCALE:      ('en_CA', 'UTF-8')
```
</details>

**Comment by khaeru** [comment]
FYI @behnam-zakeri @LauWien 
- The problem seems to be with the code added in #509.
- I find that the tests added in that PR fail on my system with various errors.
- Can you say what version(s) of GAMS you were running locally as you developed this?

**Comment by LauWien** [comment]
> * version(s) of GAMS

I use GAMS version 35.2.0.

**Comment by LauWien** [comment]
I just ran all tests and for me the tutorials added here ran through, only `test_tutorial[R_austria_load_scenario]` and `test_tutorial[R_austria]` don't, but these never do since `jupyter_client.kernelspec.NoSuchKernel: No such kernel named IR`, which I didn't install yet.

**Comment by khaeru** [comment]
> I use GAMS version 35.2.0.

Okay, and CI I believe uses a pretty recent version as well. As you can see, my local install is still on 24.

- We don't have a strict/format minimum GAMS version, except I think for MESSAGE-MACRO.
- Maybe this is something that has changed between GAMS versions, i.e. the list of acceptable characters in the descriptive text after an item declaration used to exclude `()=,` etc., but now allows some of them.
- I don't think it's necessary to track down precisely where; rather we can just apply the fix that I found worked for me locally.

**Comment by LauWien** [comment]
> recent version

Hm, just out of curiosity, checking [here ](https://github.com/iiasa/message_ix/runs/4953007199?check_suite_focus=true) it says GAMS version 25.1.1 is used or maybe I'm mistaken.

>  just apply the fix that I found worked for me locally.

Sounds good, happy to implement it.
