### ISSUE TITLE
Address failing black lint

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#555]
Since https://github.com/iiasa/message_ix/pull/554 the following files are not in black style anymore, please see [here](https://github.com/iiasa/message_ix/runs/5034018924?check_suite_focus=true). 

```
would reformat message_ix/macro.py
would reformat message_ix/tests/test_cli.py
would reformat message_ix/testing/__init__.py
```

This is due to the [new black release](https://pypi.org/project/black/) on Jan 29, 2022.

- Remove spaces around power operators if both operands are simple (#2726)

**Comment by khaeru** [comment]
Here's the changelog entry for black 22.1.0, including specific syntax changes: https://black.readthedocs.io/en/stable/change_log.html#id1
