### ISSUE TITLE
Anaconda wrongly installs message-ix=1.0.0 from arch-specific channel

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#558]
At one point Anaconda started to install version `message-ix=1.0.0` instead of the latest, e.g 3.4.0.

Forcing `conda install message-ix">1"` leads to the correct installation of `message-ix`, however with a very high memory usage/runtime (up to 45 minutes) of the conda solver on Windows. Due to that, the GitHub Actions workflow, to check this installation process, runs out of memory and cannot complete on the windows-latest actions runners (see [here](https://github.com/iiasa/message_ix/runs/5109619938?check_suite_focus=true) for an example). Locally this results in an installation time of up to 45 minutes (https://github.com/iiasa/message_ix/issues/562).

The issue was discussed (at length) in conda-forge/admin-requests#385, where conda-forge staff:
- identified it as “a solver issue”.
- offered suggestions for debugging that did not yield direct information on the cause.

At https://github.com/conda-forge/admin-requests/pull/385#issuecomment-1030871656, the following were further suggested:
- conda/conda-build#4104.
- conda/infra#514

…however, experimentation at #554 shows that the suggested workaround (`--repodata-fn repodata.json`) does not solve the problem.

This issue is to accumulate information and track efforts to get this resolved upstream.

**Comment by maximikos** [comment]
A brief comment on this. When trying to re-install `message-ix` (which did not work for me, see #584), I initially also tried with `conda install message-ix">1"`. This, however, installed only version 1.0.0. Only when forcing the installation of a specific version, like `conda install message-ix"=3.4"`, the newest/specified version got installed.

(I'm running everything in the Anaconda prompt on a Windows machine)

**Comment by khaeru** [comment]
> When trying to re-install message-ix (which did not work for me, see https://github.com/iiasa/message_ix/issues/584), I initially also tried with `conda install message-ix">1"`. This, however, installed only version 1.0.0. Only when forcing the installation of a specific version, like `conda install message-ix"=3.4"`, the newest/specified version got installed.

This is also what we discovered in #541 and #554, and you can see this reflected on the `main` branch in the daily check that installation from conda works:
https://github.com/iiasa/message_ix/blob/2045b07c13322ce0224ce809ca1c64c1e5f64398/.github/workflows/conda.yaml#L70

#545 updated to the documentation, but only to the earlier ">1", which turned out not to be the final workaround.

With conda-forge/admin-requests#385 merged, we can now do #585, after which none of these should be necessary.
