### ISSUE TITLE
Copying and using MESSAGEix GAMS files as part of Anaconda installation on Windows 10 does not work

### ISSUE THREAD

**Issue by volker-krey** [iiasa/message_ix#560]
Following the [MESSAGEix installation instructions](https://docs.messageix.org/en/stable/install.html#copy-gams-model-files-for-editing) I wanted to copy (and use) the GAMS code to a separate folder for editing `message-ix copy-model --set-default /path/for/model/files`. The copying did not work with exception of the folder structure. Error output said _file exists, will not overwrite_ for all files. In addition, the `ixmp.config/config.json` file was successfully modified to include the specified path under the `message model dir` argument. However, even after copying the GAMS code manually to the specified folder, MESSAGEix continues to be run in the Anaconda message_ix package folder `anaconda3/envs/message_env/Lib/site-packages/message_ix/model`.

The environment I am using is Windows 10, Anaconda 2021.11/Python 3.10.2, message_ix 3.4.0. Note that I have looked #416 which describes the same issue, but without suggesting a solution to the problem.

**Comment by khaeru** [comment]
> The copying did not work with exception of the folder structure. Error output said _file exists, will not overwrite_ for all files.

Is the issue that the files indeed already exist, and you want to overwrite them? If so, did you try `--overwrite`? https://github.com/iiasa/message_ix/blob/main/message_ix/cli.py#L28

Or, are you using a new/non-existent target path with `copy-model`?

**Comment by volker-krey** [comment]
The folder that I am trying to copy the files to is empty. Despite of this, for each file to be  transferred, I get an error message of the following type `\path to model\MESSAGE\version_check.gms exists, will not overwrite`. Using the `--overwrite flag`, interestingly leads to an error message of the following kind `PermissionError: [Errno 13] Permission denied: '\path to anaconda3\\envs\\message_env\\lib\\site-packages\\message_ix\\model\\data'` -- so a permission in the source, not the destination folder. 

However, copying the files is easy to fix by doing so manually. What is trickier is the fact that despite the `ixmp.config/config.json` file being successfully modified to include the specified path under the `message model dir` argument, MESSAGEix continues to be run in the anaconda3 folder. Therefore, the whole idea of having the MESSAGEix GAMS in a place where it can be modified more easily is defeated.
