### ISSUE TITLE
context manager for commits

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#564]
It would be useful to have a context manager for making scenario edits, e.g.

```
with scen.check_out(message='updating foo'):
    scen.add_par('foo', foo)
```

**Comment by khaeru** [comment]
https://docs.messageix.org/projects/ixmp/en/stable/api.html?highlight=transact#ixmp.TimeSeries.transact
https://docs.messageix.org/en/stable/api.html?highlight=transact#message_ix.Scenario.transact

**Comment by gidden** [comment]
Awesome!
