### ISSUE TITLE
Cleaning of `cplex.opt` causes asyncronous issues with multiple runs

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#575]
I have experienced silent errors when performing multiple `message_ix.Scenario.solve()`s simultaneously on the same computer. As best I can tell, these occur when I employ the `solve_options` kwarg, which forces a writing to disk of the `cplex.opt` file. 

Upon completion, I believe this file is then garbage collected. However, other solves occuring simultaneously expect for this file to be present. 

As a short solution, I would suggest we simply do not erase the file. A better solution would employ asyncronous file manipulation.

**Comment by gidden** [comment]
As I look through the code base, it seems like this was a known issue at the time, specifically citing [this](https://github.com/iiasa/message_ix/blob/main/message_ix/models.py#L368) comment.

**Comment by khaeru** [comment]
This may also be a duplicate of #250.

**Comment by gidden** [comment]
closed via #657
