### ISSUE TITLE
Pint 0.19.0 causes failures in conda CI workflow

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#577]
Possible due to the new `pint` release, all jobs in the conda.yaml workflow are failing [here](https://github.com/iiasa/message_ix/runs/5845259215?check_suite_focus=true) on the new `pint` version 0.19. Test were still succeeding on `pint=0.18` [here](https://github.com/iiasa/message_ix/runs/5828013207?check_suite_focus=true). 
The following issue was already filed https://github.com/hgrecco/pint/issues/1498. Please see also https://github.com/IAMconsortium/units/pull/37 and the [thread](https://iiasa-ece.slack.com/archives/CD0GBHHA4/p1649144953896939) in the #message_general slack channel by @khaeru.

**Comment by khaeru** [comment]
Thanks for noting this here.

I expect the upstream fix will come out quickly, so I think we just tolerate the failures for a few days and then confirm that the fix will resolve them. To adjust workflows (not just here, but in other repos) and then reset them would be more work.

**Comment by LauWien** [comment]
The now [failing jobs on windows-latest](https://github.com/iiasa/message_ix/runs/5862737618?check_suite_focus=true) were also already filed in the same issue https://github.com/hgrecco/pint/issues/1498#issuecomment-1090345520 and will be dealt with upstream.

**Comment by khaeru** [comment]
Per https://github.com/iiasa/message_ix/pull/585#issuecomment-1107845032 this is now resolved.
