### ISSUE TITLE
Key errors,  after running my first cell in my model,  with new Message-ix 3.4 version

### ISSUE THREAD

**Issue by PelinaP** [iiasa/message_ix#590]
This my first part of code

##### load required packages 
import itertools
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

import ixmp as ix
import message_ix

from message_ix.utils import make_df
from tools import Plots

<!-- after i run this cell, i got the following errors

 File "<string>", line 6
DefinitionSyntaxError: Could not add Context AR6GWP100 relation on line '6'

ile "C:\Users\energy\anaconda3\lib\site-packages\pint\registry.py", line 802, in _get_dimensionality_recurse
    reg = self._dimensions[key]

KeyError: '[_GWP]'

#### Versions 3.4 message-ix

kindly explain this errors.

**Comment by LauWien** [comment]
Dear @PelinaP, as I understand this new issue you filed is an answer to the following [comment](https://github.com/iiasa/message_ix/issues/589#issuecomment-1110842795) in issue https://github.com/iiasa/message_ix/issues/589. 
Please comment under https://github.com/iiasa/message_ix/issues/589, with the correct way of pasting code, as @khaeru mentioned [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code), as I will close this issue. Many thanks in advance!

**Comment by PelinaP** [comment]
Please help me . I have followed instructions on how to paste. But still
not correct
