### ISSUE TITLE
An error from the "Austria" tutorial

### ISSUE THREAD

**Issue by Jihoon** [iiasa/message_ix#62]
Ok, I am a beginner here, and it is also likely that I didn't do it right.

I installed MESSAGEix through Anaconda and got the tutorial through messageix-dl. Then, when I ran the whole thing without any changes, I see this at the line "scenario.solve()":

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-45-6454e8d7b2fb> in <module>()
----> 1 scenario.solve()

TypeError: solve() missing 1 required positional argument: 'model'
---------------------------------------------------------------------------

Is it supposed to run ok? Following Matt's suggestion, when I do scenario.solve('MESSAGE'), it runs fine.

**Comment by gidden** [comment]
The issue here is related to the version the tutorial uses relative to the version installed. I'll make an issue.

**Comment by gidden** [comment]
closing in favor of #64
