### ISSUE TITLE
Wrong import of make_df in austria_tutorial.ipynb

### ISSUE THREAD

**Issue by fwitte** [iiasa/message_ix#634]
make_df is imported from the wrong location. It should be `from message_ix.utils import make_df`  instead of `from message_ix.util import make_df`.

**Comment by khaeru** [comment]
The bug report template prompts you to give the version of message_ix and other packages you are using. While you don't say here, I guess from https://github.com/iiasa/message_ix/issues/620#issuecomment-1201115359 that you are using message_ix 3.1.0.

`message_ix.utils` no longer exists as of 3.2.0: https://github.com/iiasa/message_ix/blob/51ccdfb631e815bc4142df45650f908900c9dbf6/message_ix/utils.py#L7-L11

`make_df()` is intended to be imported from the top-level, i.e. `from message_ix import make_df`, although it can also be imported from `message_ix.util`.
