### ISSUE TITLE
GAMS/Cplex  does not solve MIP

### ISSUE THREAD

**Issue by PelinaP** [iiasa/message_ix#647]
Error Cannot open parameter file "C:\Users\energy\anaconda3\envs\message_env\Lib\site-packages\message_ix\model\cplex.opt"
*** Error Error code = 2; No such file or directory
----

#### Code sample or context
I downloaded new version of Message-ix 3.6 and also gams version of 34.3. The cplex model worked fine with gams version 30.3 and message-ix version 3.0 . I would like to find out why i recieve error message 
GAMS/Cplex Link licensed for continuous and discrete problems.

*** Error Cannot open parameter file "C:\Users\energy\anaconda3\envs\message_env\Lib\site-packages\message_ix\model\cplex.opt"
*** Error Error code = 2; No such file or directory

# ...your code

-->scenario.init_set("kp")

#### Expected result

 feasible solution and cplex should work fine

#### Problem description
Error message ; Cannot open parameter file "C:\Users\energy\anaconda3\envs\message_env\Lib\site-packages\message_ix\model\cplex.opt"
*** Error Error code = 2; No such file or directory

#### Versions 
Gams version 34.3 , message-ix 3.6
####Output 
--- Space for names approximately 1.37 Mb
--- Use option 'names no' to turn use of names off
--- GMO memory 5.87 Mb (peak 5.96 Mb)
--- Dictionary memory 0.00 Mb
--- Cplex 20.1.0.0 link memory 0.38 Mb (peak 2.68 Mb)
--- Starting Cplex

Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
CPXPARAM_Advance                                 0
CPXPARAM_Threads                                 1
CPXPARAM_MIP_Display                             4
CPXPARAM_Simplex_Limits_Iterations               100000000
CPXPARAM_TimeLimit                               1000000
CPXPARAM_MIP_Tolerances_AbsMIPGap                0
CPXPARAM_MIP_Tolerances_MIPGap                   0
Generic callback                                 0x50
Row 'INTP_CAP(Zambia,'Oil(FO)_ppl',2025)' infeasible, all entries at implied bounds.
Presolve time = 0.00 sec. (5.54 ticks)

Root node processing (before b&c):
  Real time             =    0.02 sec. (8.25 ticks)
Sequential b&c:
  Real time             =    0.00 sec. (0.00 ticks)
                          ------------
Total (root+branch&cut) =    0.02 sec. (8.25 ticks)

--- MIP status (103): integer infeasible.
--- Cplex Time: 0.02sec (det. 8.29 ticks)

CPLEX Error  1217: No solution exists.
--- Problem is integer infeasible
```
<!--
Run one of the following and paste the results here:
- 'message-ix show-versions' in a terminal, or
- 'import ixmp; ixmp.show_versions()' in a Python interpreter.
-->
```

**Comment by volker-krey** [comment]
The original GAMS coming with `message_ix` does not include any mixed integer program (MIP) model specification. If you modified the GAMS code and added a MIP version of  `message_ix`, it is difficult for us to help with that. The error message related to the file `cplex.opt` not existing should not be the reason for the infeasibility of the problem. `cplex.opt` is an optional file to set solver-specific options for CPLEX, a subset of which can be set via the [Python API](https://docs.messageix.org/en/stable/api.html?highlight=cplex.opt#message_ix.models.DEFAULT_CPLEX_OPTIONS).
