### ISSUE TITLE
Levelized costs not calculated for technologies with only `var_cost`

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#652]
The `levelized_cost` are used to determine the penalty associated with the additional relaxation of dynamic constraints via the `soft_activity_lo/_up` in combination with `level_cost_activity_soft_lo/_up`. 

Currently, the calculation of [levelized_costs](https://github.com/iiasa/message_ix/blob/1680452d53ed646eca1b84e7446da0f255d8351c/message_ix/model/MESSAGE/scaling_investment_costs.gms#L35) excludes all technologies which do not have investment-costs parametrized. This means that for technologies where only variable costs are specified, the "soft" relaxation is without cost.

#### Expected result
If for a technology only the parameter `var_cost` has been defined, then `levelized_cost` are calculated.

#### Problem description
If for a technology only the parameter `var_cost` has been defined, then `levelized_cost` are NOT calculated.

#### Versions

v3.6

**Comment by behnam-zakeri** [comment]
@OFR-IIASA thanks for opening this. I believe `levelized_cost` is defined as the cost of one unit of _capacity_ of a given technology levelized over the lifetime. So, indeed it's a capacity-related parameter, and should be read as "Levelized cost of one unit of capacity". This is not equal to what is more commonly known as "Levelized cost of electricity" or LCOE. I have two suggestions for the way forward:
- making the definition clear in the documentation
- including `relation_cost` in the formulation
- defining another auxiliary parameter for "levelized cost of one unit of output commodity" for technologies. This has been a desirable feature, and I believe you and @Jihoon have worked previously to calculate.
