### ISSUE TITLE
Macro: solve method for message doesnt correspond with cplexopt

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#66]
cplex.opt is configured as follows:
_* CPLEX LP solution method
* see https://www.gams.com/help/topic/gams.doc/solvers/cplex/index.html#CPLEXlpmethod
* 0     Automatic
* 1     Primal Simplex
* 2     Dual Simplex
* 3     Network Simplex
* 4     Barrier
* 5     Sifting
* 6     Concurrent

lpmethod = 4
threads = 4
epopt 1e-6_

When message initially solves, the barrier method is applied and solves quickly. After macro solves and runs message with updated demands, the primal simplex method is applied despite being configured otherwise. Maybe i dont understand how the barrier algorithm works, but the current solving of macro-initiated solving is very slow and may benefit from using a different solution method.  

See log below:
_--- MESSAGE-MACRO_run.gms(4019) 778 Mb
--- LOOPS iteration = 2
---   469,900 rows  398,378 columns  3,171,485 non-zeroes
--- Executing CPLEX (Solvelink=1): elapsed 0:02:32.683

IBM ILOG CPLEX   24.9.1 r63795 Released Aug 30, 2017 WEI x86 64bit/MS Windows 
--- GAMS/Cplex Link licensed for continuous and discrete problems.
Cplex 12.7.1.0

Reading parameter(s) from "C:\Repo\message_ix\message_ix\model\cplex.opt"
>>  * CPLEX LP solution method
>>  * see https://www.gams.com/help/topic/gams.doc/solvers/cplex/index.html#CPLEXlpmethod
>>  * 0     Automatic
>>  * 1     Primal Simplex
>>  * 2     Dual Simplex
>>  * 3     Network Simplex
>>  * 4     Barrier
>>  * 5     Sifting
>>  * 6     Concurrent
>> 
>>  lpmethod = 4
>>  threads = 4
>>  epopt 1e-6
Finished reading from "C:\Repo\message_ix\message_ix\model\cplex.opt"
*** Basis supplied by GAMS will be used.
*** Use option 'advind 0' to discard basis information.
Reading data...
Starting Cplex...
Space for names approximately 47.34 Mb
Use option 'names no' to turn use of names off
CPXPARAM_Advance                                 2
CPXPARAM_TimeLimit                               1000000
CPXPARAM_LPMethod                                4
CPXPARAM_Threads                                 4
CPXPARAM_Parallel                                1
CPXPARAM_Tune_TimeLimit                          200000
CPXPARAM_Barrier_Limits_Iteration                100000000
Parallel mode: deterministic, using up to 4 threads for concurrent optimization.

Iteration log . . .
Iteration:     1   Dual objective     =       1889662.827424
Markowitz threshold set to 0.1
Iteration:    24   Dual objective     =       1889664.236562
Iteration:   667   Dual objective     =       1890028.298649
...._

**Comment by danielhuppmann** [comment]
closed via #67
