### ISSUE TITLE
Add documentation for GAMS options

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/message_ix#71]
We should add some documentation on how to change GAMS and solver options. Some of these are currently "hard-coded" in the MESSAGEix code.

**Comment by behnam2015** [comment]
any update on this? It seems the model overwrites the opt file each time when solving. And even when I make a second opt file and manually add the name of the second file to GAMS code; again, when I solve from another interface (like python), my specified method is not used. I will be thankful if someone can help to set the barrier method as default cplex method for solving my models from any envrionment.

**Comment by gidden** [comment]
Hi @behnam2015, additional options to the solver can be passed using the `solve_options` argument (see [here](https://github.com/iiasa/message_ix/blob/master/message_ix/core.py#L286))

**Comment by gidden** [comment]
So in this case you can use `solve_options={'lpmethod': '4'}` (or whichever the barrier lpmethod is)

**Comment by behnam2015** [comment]
Great! Thanks a lot @gidden!

**Comment by khaeru** [comment]
[Scenario.solve](https://message.iiasa.ac.at/en/master/api.html#message_ix.Scenario.solve), the [MESSAGE](https://message.iiasa.ac.at/en/master/api.html#message_ix.models.MESSAGE) class, [GAMSModel](https://message.iiasa.ac.at/projects/ixmp/en/latest/api-model.html#ixmp.model.gams.GAMSModel), and [DEFAULT_CPLEX_OPTIONS](https://message.iiasa.ac.at/en/master/api.html#message_ix.models.DEFAULT_CPLEX_OPTIONS) now describe these options.
