### ISSUE TITLE
Split tutorial tests to separate CI job

### ISSUE THREAD

**Issue by khaeru** [iiasa/message_ix#739]
The "pytest" CI workflow takes up to 20 minutes (Windows) to run, which makes it less useful for its intended purpose of quick feedback on PRs. Most of the 20 longest-duration tests are tutorial tests.

One way to address this:
- Add a second job named "tutorials" within the pytest.yaml workflow file.
- In this job, run only the tests of the tutorials. This might be done for only one Python version.
- In the "pytest" job, omit the test of the tutorials.

Other benefits: we could upload Codecov reports for only the "pytest" workflow. This would help us see if there is any code that is currently tested *only* through its use in a tutorial, and add more direct (faster, simpler) tests.

**Comment by glatterf42** [comment]
Thanks for adding this issue, this sounds like a helpful improvement.
