### ISSUE TITLE
Validate failed error

### ISSUE THREAD

**Issue by alexkoberle** [iiasa/message_ix#75]
When loading ixmp.Platform() there is an error migrating database:

import os
import pandas as pd
import ixmp as ix
import message_ix

dbprops = "ixmp.properties"

mp = ix.Platform() #dbtype='HSQLDB'

INFO:root:launching ixmp.Platform using config file at 'C:\Users\alexk\Documents\GitHub\ixmp\config\ixmp.properties'
Traceback (most recent call last):

 File "<ipython-input-1-40b07cde0902>", line 19, in <module>
   mp = ix.Platform() #dbtype='HSQLDB'

 File "C:\Miniconda3\lib\site-packages\ixmp\core.py", line 82, in __init__
   self._jobj = java.ixmp.Platform("Python", dbprops)

 File "C:\Miniconda3\lib\site-packages\jpype\_jclass.py", line 111, in _javaInit
   *args)

org.flywaydb.core.api.FlywayExceptionPyRaisable: org.flywaydb.core.api.FlywayException: Validate failed: Detected resolved migration not applied to database: 1.2

**Comment by danielhuppmann** [comment]
This is a known bug with ORACLE db instances. It can be fixed by deleting the flyway-migration files in the ixmp installation folder (e.g. `C:/Users/<user>/Anaconda3/Lib/site-packages/ixmp`) and then `ixmp/db/migration/oracle`. There, delete the files „V1.2…" and „V1.3…“.

Proper fix is on the way...

**Comment by ClaraLuisa** [comment]
Hey @danielhuppmann has this issue been resolved? I seem to be running into a similar issue, however, simply deleting the `flyway-core-4.2.0.jar` file in the `C:\Users\<user>\AppData\Local\Continuum\anaconda3\envs\message\Lib\site-packages\ixmp\lib` seems to not be resolving the issue. Has any other solution come up to fix this issue by now?

**Comment by danielhuppmann** [comment]
hey @ClaraLuisa, you deleted the wrong file - don't delete the `.jar` file, but delete the migration files as specified above.

Depending on when you first started using `ixmp` and `message_ix`, you may also need to delete your local HSQLDB files (or reach out bilaterally if you need to keep the old database files for manual fixing, but that's a bit of an effort).

**Comment by danielhuppmann** [comment]
This issue has been fixed in principle, let's close this after release 1.2.

**Comment by ClaraLuisa** [comment]
hey @danielhuppmann, thanks for the prompt reply! Unfortunately there are no other "flyway" files in the respective folder. 
![image](https://user-images.githubusercontent.com/16190366/56042268-f6b42c00-5d3a-11e9-8b08-e00478a6b64a.png)

The deleting might then be a problem (I tried to download and run our model from the South Africa publication).

**Comment by ClaraLuisa** [comment]
Oh, so should I simply install message-ix from source from the current v.1.2 branch?

**Comment by danielhuppmann** [comment]
If there is no folder `ixmp/db`, this means that you are on a version where the issue has been resolved.

If you are using the `hsqldb` files from the **MESSAGEix South Africa** manuscript, you need an installation version higher (or equal) to the one when you created the `hsqldb` files (and keep in mind that installing from source is ahead of the `conda` release version).

In your case, installing from the latest `iiasa:master` branch should do the trick.

**Comment by ClaraLuisa** [comment]
@danielhuppmann thanks for explaining this for the millionth time! Installing ixmp from source and then message_ix from source into a clean environment worked super smoothly, again.

**Comment by khaeru** [comment]
We have this targeted for the 1.2 release—can we consider the issue resolved?

**Comment by ClaraLuisa** [comment]
Thanks for asking @khaeru. From my point this issue has been resolved.

**Comment by khaeru** [comment]
Per @ClaraLuisa's comment, closing this as resolved with the earlier release of 1.2. @alexkoberle if it is still occurring, please re-open the issue or file a new one.
