### ISSUE TITLE
Incompatibility with genno v1.22.0

### ISSUE THREAD

**Issue by glatterf42** [iiasa/message_ix#768]
The recent release of v1.22.0 broke some CI tests for message-ix-models, but curiously only those that make use of the latest versions of iiasa/message_ix/main. See https://github.com/khaeru/genno/issues/112 for more technical details.

**Comment by khaeru** [comment]
Closing, as this bug turned out to be confined to message-ix-models. See discussion at iiasa/message-ix-models#142.
