### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by meng25meng** [iiasa/message_ix#826]
Hello, I read the data with excel and started to add parameters. When I started to add parameters, I got an error. Because my version was too old and I forgot which version I was using, I got an error when importing this utils. But I can't find which version of utils is now. , what should I do? Will it be compatible with the new version of util?
`ModuleNotFoundError                       Traceback (most recent call last)
Cell In[23], line 1
----> 1 import utils
      2 ap = utils.add_par(scenario, horizon, vintage_years, firstyear, disp_error)

ModuleNotFoundError: No module named 'utils'`

**Comment by khaeru** [comment]
When you open an issue on this repository there is a template ([this one](https://github.com/iiasa/message_ix/blob/main/.github/ISSUE_TEMPLATE/bug.md)) that asks you to give certain information—including "the output of `message-ix show-versions`".

To be very clear, without this information *we cannot provide you with assistance*.

Please update your issue description to include the items mentioned in the template.

**Comment by glatterf42** [comment]
Continued in #830.
