### ISSUE TITLE
Accidentally openend issue

### ISSUE THREAD

**Issue by meng25meng** [iiasa/message_ix#829]
When you open an issue on this repository there is a template ([this one](https://github.com/iiasa/message_ix/blob/main/.github/ISSUE_TEMPLATE/bug.md)) that asks you to give certain information—including "the output of `message-ix show-versions`".

To be very clear, without this information *we cannot provide you with assistance*.

Please update your issue description to include the items mentioned in the template.

_Originally posted by @khaeru in https://github.com/iiasa/message_ix/issues/826#issuecomment-2067645510_

**Comment by glatterf42** [comment]
Referencing @khaeru's comment in a new issue was probably not what you had in mind. Don't worry about accidentally opening issues, but please close them to keep our list of issues clean :)
